(setq includeme! '(
("ATOMIC_BOOL_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR16_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR32_LOCK_FREE" stdatomic.h)
("ATOMIC_CHAR_LOCK_FREE" stdatomic.h)
("ATOMIC_INT_LOCK_FREE" stdatomic.h)
("ATOMIC_LLONG_LOCK_FREE" stdatomic.h)
("ATOMIC_LONG_LOCK_FREE" stdatomic.h)
("ATOMIC_POINTER_LOCK_FREE" stdatomic.h)
("ATOMIC_SHORT_LOCK_FREE" stdatomic.h)
("ATOMIC_VAR_INIT" stdatomic.h)
("ATOMIC_WCHAR_T_LOCK_FREE" stdatomic.h)
("BUFSIZ" stdio.h)
("CHAR_BIT" stdint.h)
("CHAR_MAX" stdint.h)
("CHAR_MIN" stdint.h)
("CMSG_ALIGN" sys/socket.h)
("CMSG_DATA" sys/socket.h)
("CMSG_FIRSTHDR" sys/socket.h)
("CMSG_LEN" sys/socket.h)
("CMSG_NXTHDR" sys/socket.h)
("CMSG_SPACE" sys/socket.h)
("CPU_ALLOC" sched.h)
("CPU_ALLOC_SIZE" sched.h)
("CPU_AND" sched.h)
("CPU_AND_S" sched.h)
("CPU_CLR" sched.h)
("CPU_CLR_S" sched.h)
("CPU_COUNT" sched.h)
("CPU_COUNT_S" sched.h)
("CPU_EQUAL" sched.h)
("CPU_EQUAL_S" sched.h)
("CPU_FREE" sched.h)
("CPU_ISSET" sched.h)
("CPU_ISSET_S" sched.h)
("CPU_OR" sched.h)
("CPU_OR_S" sched.h)
("CPU_SET" sched.h)
("CPU_SET_S" sched.h)
("CPU_XOR" sched.h)
("CPU_XOR_S" sched.h)
("CPU_ZERO" sched.h)
("CPU_ZERO_S" sched.h)
("DBL_DIG" stdint.h)
("DBL_EPSILON" stdint.h)
("DBL_MANT_DIG" stdint.h)
("DBL_MAX" stdint.h)
("DBL_MAX_10_EXP" stdint.h)
("DBL_MAX_EXP" stdint.h)
("DBL_MIN" stdint.h)
("DBL_MIN_10_EXP" stdint.h)
("DBL_MIN_EXP" stdint.h)
("DECIMAL_DIG" stdint.h)
("DES_FAILED" rpc/des_crypt.h)
("EOF" stdio.h)
("EXIT_FAILURE" stdlib.h)
("EXIT_SUCCESS" stdlib.h)
("FD_CLR" sys/select.h unistd.h sys/types.h sys/time.h)
("FD_ISSET" sys/select.h unistd.h sys/types.h sys/time.h)
("FD_SET" sys/select.h unistd.h sys/types.h sys/time.h)
("FD_ZERO" sys/select.h unistd.h sys/types.h sys/time.h)
("FE_ALL_EXCEPT" fenv.h)
("FE_DFL_ENV" fenv.h)
("FE_DIVBYZERO" fenv.h)
("FE_DOWNWARD" fenv.h)
("FE_INEXACT" fenv.h)
("FE_INVALID" fenv.h)
("FE_OVERFLOW" fenv.h)
("FE_TONEAREST" fenv.h)
("FE_TOWARDZERO" fenv.h)
("FE_UNHERFLOW" fenv.h)
("FE_UPWARD" fenv.h)
("FILE" stdio.h)
("FILENAME_MAX" stdio.h)
("FLT_DIG" stdint.h)
("FLT_EPSILON" stdint.h)
("FLT_EVAL_METHOD" float.h)
("FLT_MANT_DIG" stdint.h)
("FLT_MAX" stdint.h)
("FLT_MAX_10_EXP" stdint.h)
("FLT_MAX_EXP" stdint.h)
("FLT_MIN" stdint.h)
("FLT_MIN_10_EXP" stdint.h)
("FLT_MIN_EXP" stdint.h)
("FLT_RADIX" stdint.h)
("FLT_ROUNDS" float.h)
("FOPEN_MAX" stdio.h)
("HUGE_VAL" math.h)
("HUGE_VALF" math.h)
("HUGE_VALL" math.h)
("INT16_MAX" stdint.h)
("INT16_MIN" stdint.h)
("INT32_MAX" stdint.h)
("INT32_MIN" stdint.h)
("INT64_MAX" stdint.h)
("INT64_MIN" stdint.h)
("INT8_MAX" stdint.h)
("INT8_MIN" stdint.h)
("INTMAX_MAX" stdint.h)
("INTMAX_MIN" stdint.h)
("INTPTR_MAX" stdint.h)
("INTPTR_MIN" stdint.h)
("INT_FAST16_MAX" stdint.h)
("INT_FAST16_MIN" stdint.h)
("INT_FAST32_MAX" stdint.h)
("INT_FAST32_MIN" stdint.h)
("INT_FAST64_MAX" stdint.h)
("INT_FAST64_MIN" stdint.h)
("INT_FAST8_MAX" stdint.h)
("INT_FAST8_MIN" stdint.h)
("INT_LEAST16_MAX" stdint.h)
("INT_LEAST16_MIN" stdint.h)
("INT_LEAST32_MAX" stdint.h)
("INT_LEAST32_MIN" stdint.h)
("INT_LEAST64_MAX" stdint.h)
("INT_LEAST64_MIN" stdint.h)
("INT_LEAST8_MAX" stdint.h)
("INT_LEAST8_MIN" stdint.h)
("INT_MAX" stdint.h)
("INT_MIN" stdint.h)
("LDBL_DIG" stdint.h)
("LDBL_EPSILON" stdint.h)
("LDBL_MANT_DIG" stdint.h)
("LDBL_MAX" stdint.h)
("LDBL_MAX_10_EXP" stdint.h)
("LDBL_MAX_EXP" stdint.h)
("LDBL_MIN" stdint.h)
("LDBL_MIN_10_EXP" stdint.h)
("LDBL_MIN_EXP" stdint.h)
("LLONG_MAX" stdint.h)
("LLONG_MIN" stdint.h)
("LONG_MAX" stdint.h)
("LONG_MIN" stdint.h)
("L_tmpnam" stdio.h)
("MB_LEN_MAX" stdint.h)
("NLMSG_ALIGN" asm/types.h linux/netlink.h)
("NLMSG_DATA" asm/types.h linux/netlink.h)
("NLMSG_LENGTH" asm/types.h linux/netlink.h)
("NLMSG_NEXT" asm/types.h linux/netlink.h)
("NLMSG_OK" asm/types.h linux/netlink.h)
("NLMSG_PAYLOAD" asm/types.h linux/netlink.h)
("NLMSG_SPACE" asm/types.h linux/netlink.h)
("ONCE_FLAG_INIT" threads.h)
("PRIX16" stdint.h)
("PRIX32" stdint.h)
("PRIX64" stdint.h)
("PRIX8" stdint.h)
("PRIXFAST16" stdint.h)
("PRIXFAST32" stdint.h)
("PRIXFAST64" stdint.h)
("PRIXFAST8" stdint.h)
("PRIXLEAST16" stdint.h)
("PRIXLEAST32" stdint.h)
("PRIXLEAST64" stdint.h)
("PRIXLEAST8" stdint.h)
("PRIXMAX" stdint.h)
("PRIXPTR " stdint.h)
("PRId16" stdint.h)
("PRId32" stdint.h)
("PRId64" stdint.h)
("PRId8" stdint.h)
("PRIdFAST16" stdint.h)
("PRIdFAST32" stdint.h)
("PRIdFAST64" stdint.h)
("PRIdFAST8" stdint.h)
("PRIdLEAST16" stdint.h)
("PRIdLEAST32" stdint.h)
("PRIdLEAST64" stdint.h)
("PRIdLEAST8" stdint.h)
("PRIdMAX" stdint.h)
("PRIdPTR " stdint.h)
("PRIi16" stdint.h)
("PRIi32" stdint.h)
("PRIi64" stdint.h)
("PRIi8" stdint.h)
("PRIiFAST16" stdint.h)
("PRIiFAST32" stdint.h)
("PRIiFAST64" stdint.h)
("PRIiFAST8" stdint.h)
("PRIiLEAST16" stdint.h)
("PRIiLEAST32" stdint.h)
("PRIiLEAST64" stdint.h)
("PRIiLEAST8" stdint.h)
("PRIiMAX" stdint.h)
("PRIiPTR " stdint.h)
("PRIo16" stdint.h)
("PRIo32" stdint.h)
("PRIo64" stdint.h)
("PRIo8" stdint.h)
("PRIoFAST16" stdint.h)
("PRIoFAST32" stdint.h)
("PRIoFAST64" stdint.h)
("PRIoFAST8" stdint.h)
("PRIoLEAST16" stdint.h)
("PRIoLEAST32" stdint.h)
("PRIoLEAST64" stdint.h)
("PRIoLEAST8" stdint.h)
("PRIoMAX" stdint.h)
("PRIoPTR " stdint.h)
("PRIu16" stdint.h)
("PRIu32" stdint.h)
("PRIu64" stdint.h)
("PRIu8" stdint.h)
("PRIuFAST16" stdint.h)
("PRIuFAST32" stdint.h)
("PRIuFAST64" stdint.h)
("PRIuFAST8" stdint.h)
("PRIuLEAST16" stdint.h)
("PRIuLEAST32" stdint.h)
("PRIuLEAST64" stdint.h)
("PRIuLEAST8" stdint.h)
("PRIuMAX" stdint.h)
("PRIuPTR " stdint.h)
("PRIx16" stdint.h)
("PRIx32" stdint.h)
("PRIx64" stdint.h)
("PRIx8" stdint.h)
("PRIxFAST16" stdint.h)
("PRIxFAST32" stdint.h)
("PRIxFAST64" stdint.h)
("PRIxFAST8" stdint.h)
("PRIxLEAST16" stdint.h)
("PRIxLEAST32" stdint.h)
("PRIxLEAST64" stdint.h)
("PRIxLEAST8" stdint.h)
("PRIxMAX" stdint.h)
("PRIxPTR " stdint.h)
("PTRDIFF_MAX" stdint.h)
("PTRDIFF_MIN" stdint.h)
("RAND_MAX" stdlib.h)
("RTA_DATA" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("RTA_LENGTH" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("RTA_NEXT" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("RTA_OK" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("RTA_PAYLOAD" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("RTA_SPACE" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("SCHAR_MAX" stdint.h)
("SCHAR_MIN" stdint.h)
("SCNX16" stdint.h)
("SCNX32" stdint.h)
("SCNX64" stdint.h)
("SCNX8" stdint.h)
("SCNXFAST16" stdint.h)
("SCNXFAST32" stdint.h)
("SCNXFAST64" stdint.h)
("SCNXFAST8" stdint.h)
("SCNXLEAST16" stdint.h)
("SCNXLEAST32" stdint.h)
("SCNXLEAST64" stdint.h)
("SCNXLEAST8" stdint.h)
("SCNXMAX" stdint.h)
("SCNXPTR" stdint.h)
("SCNd16" stdint.h)
("SCNd32" stdint.h)
("SCNd64" stdint.h)
("SCNd8" stdint.h)
("SCNdFAST16" stdint.h)
("SCNdFAST32" stdint.h)
("SCNdFAST64" stdint.h)
("SCNdFAST8" stdint.h)
("SCNdLEAST16" stdint.h)
("SCNdLEAST32" stdint.h)
("SCNdLEAST64" stdint.h)
("SCNdLEAST8" stdint.h)
("SCNdMAX" stdint.h)
("SCNdPTR " stdint.h)
("SCNi16" stdint.h)
("SCNi32" stdint.h)
("SCNi64" stdint.h)
("SCNi8" stdint.h)
("SCNiFAST16" stdint.h)
("SCNiFAST32" stdint.h)
("SCNiFAST64" stdint.h)
("SCNiFAST8" stdint.h)
("SCNiLEAST16" stdint.h)
("SCNiLEAST32" stdint.h)
("SCNiLEAST64" stdint.h)
("SCNiLEAST8" stdint.h)
("SCNiMAX" stdint.h)
("SCNiPTR " stdint.h)
("SCNo16" stdint.h)
("SCNo32" stdint.h)
("SCNo64" stdint.h)
("SCNo8" stdint.h)
("SCNoFAST16" stdint.h)
("SCNoFAST32" stdint.h)
("SCNoFAST64" stdint.h)
("SCNoFAST8" stdint.h)
("SCNoLEAST16" stdint.h)
("SCNoLEAST32" stdint.h)
("SCNoLEAST64" stdint.h)
("SCNoLEAST8" stdint.h)
("SCNoMAX" stdint.h)
("SCNoPTR " stdint.h)
("SCNu16" stdint.h)
("SCNu32" stdint.h)
("SCNu64" stdint.h)
("SCNu8" stdint.h)
("SCNuFAST16" stdint.h)
("SCNuFAST32" stdint.h)
("SCNuFAST64" stdint.h)
("SCNuFAST8" stdint.h)
("SCNuLEAST16" stdint.h)
("SCNuLEAST32" stdint.h)
("SCNuLEAST64" stdint.h)
("SCNuLEAST8" stdint.h)
("SCNuMAX" stdint.h)
("SCNuPTR " stdint.h)
("SCNx16" stdint.h)
("SCNx32" stdint.h)
("SCNx64" stdint.h)
("SCNx8" stdint.h)
("SCNxFAST16" stdint.h)
("SCNxFAST32" stdint.h)
("SCNxFAST64" stdint.h)
("SCNxFAST8" stdint.h)
("SCNxLEAST16" stdint.h)
("SCNxLEAST32" stdint.h)
("SCNxLEAST64" stdint.h)
("SCNxLEAST8" stdint.h)
("SCNxMAX" stdint.h)
("SCNxPTR " stdint.h)
("SEEK_CUR" stdio.h)
("SEEK_END" stdio.h)
("SEEK_SET" stdio.h)
("SHRT_MAX" stdint.h)
("SHRT_MIN" stdint.h)
("SIGABRT" signal.h)
("SIGFPE" signal.h)
("SIGILL" signal.h)
("SIGINT" signal.h)
("SIGSEGV" signal.h)
("SIGTERM" signal.h)
("SIG_ATOMIC_MAX" stdint.h)
("SIG_ATOMIC_MIN" stdint.h)
("SIG_ERR" signal.h)
("SIZE_MAX" stdint.h)
("TMP_MAX" stdio.h)
("TSS_DTOR_ITERATIONS" threads.h)
("UCHAR_MAX" stdint.h)
("UINT16_MAX" stdint.h)
("UINT32_MAX" stdint.h)
("UINT64_MAX" stdint.h)
("UINT8_MAX" stdint.h)
("UINTMAX_MAX" stdint.h)
("UINTPTR_MAX" stdint.h)
("UINT_FAST16_MAX" stdint.h)
("UINT_FAST32_MAX" stdint.h)
("UINT_FAST64_MAX" stdint.h)
("UINT_FAST8_MAX" stdint.h)
("UINT_LEAST16_MAX" stdint.h)
("UINT_LEAST32_MAX" stdint.h)
("UINT_LEAST64_MAX" stdint.h)
("UINT_LEAST8_MAX" stdint.h)
("UINT_MAX" stdint.h)
("ULLONG_MAX" stdint.h)
("ULONG_MAX" stdint.h)
("USHRT_MAX" stdint.h)
("WCHAR_MAX" stdint.h)
("WCHAR_MIN" stdint.h)
("WINT_MAX" stdint.h)
("WINT_MIN" stdint.h)
("_Exit" stdlib.h unistd.h)
("_IOFBF" stdio.h)
("_IOLBF" stdio.h)
("_IONBF" stdio.h)
("__fbufsize" stdio_ext.h stdio.h)
("__flbf" stdio_ext.h stdio.h)
("__fpending" stdio_ext.h stdio.h)
("__fpurge" stdio_ext.h stdio.h)
("__freadable" stdio_ext.h stdio.h)
("__freading" stdio_ext.h stdio.h)
("__fsetlocking" stdio_ext.h stdio.h)
("__fwritable" stdio_ext.h stdio.h)
("__fwriting" stdio_ext.h stdio.h)
("__setfpucw" i386/fpu_control.h)
("_exit" unistd.h)
("_flushlbf" stdio_ext.h stdio.h)
("_llseek" unistd.h sys/types.h)
("_sysctl" unistd.h linux/sysctl.h)
("a64l" stdlib.h)
("abs" stdlib.h)
("accept" sys/socket.h sys/types.h)
("accept4" sys/socket.h sys/types.h)
("access" unistd.h)
("acct" unistd.h)
("acos" math.h)
("acosf" math.h)
("acosh" math.h)
("acoshf" math.h)
("acoshl" math.h)
("acosl" math.h)
("add_key" keyutils.h)
("addmntent" mntent.h stdio.h)
("addseverity" fmtmsg.h)
("adjtimex" sys/timex.h)
("aio_cancel" aio.h)
("aio_error" aio.h)
("aio_fsync" aio.h)
("aio_init" aio.h)
("aio_read" aio.h)
("aio_return" aio.h)
("aio_suspend" aio.h)
("aio_write" aio.h)
("alarm" unistd.h)
("alloca" alloca.h)
("alphasort" dirent.h)
("arch_prctl" asm/prctl.h sys/prctl.h)
("argz_add" argz.h)
("argz_add_sep" argz.h)
("argz_append" argz.h)
("argz_count" argz.h)
("argz_create" argz.h)
("argz_create_sep" argz.h)
("argz_delete" argz.h)
("argz_extract" argz.h)
("argz_insert" argz.h)
("argz_next" argz.h)
("argz_replace" argz.h)
("argz_stringify" argz.h)
("asctime" time.h)
("asctime_r" time.h)
("asin" math.h)
("asinf" math.h)
("asinh" math.h)
("asinhf" math.h)
("asinhl" math.h)
("asinl" math.h)
("asn1_array2tree" libtasn1.h)
("asn1_bit_der" libtasn1.h)
("asn1_check_version" libtasn1.h)
("asn1_copy_node" libtasn1.h)
("asn1_create_element" libtasn1.h)
("asn1_delete_element" libtasn1.h)
("asn1_delete_structure" libtasn1.h)
("asn1_der_coding" libtasn1.h)
("asn1_der_decoding" libtasn1.h)
("asn1_der_decoding_element" libtasn1.h)
("asn1_der_decoding_startEnd" libtasn1.h)
("asn1_expand_any_defined_by" libtasn1.h)
("asn1_expand_octet_string" libtasn1.h)
("asn1_find_node" libtasn1.h)
("asn1_find_structure_from_oid" libtasn1.h)
("asn1_get_bit_der" libtasn1.h)
("asn1_get_length_ber" libtasn1.h)
("asn1_get_length_der" libtasn1.h)
("asn1_get_octet_der" libtasn1.h)
("asn1_get_tag_der" libtasn1.h)
("asn1_length_der" libtasn1.h)
("asn1_number_of_elements" libtasn1.h)
("asn1_octet_der" libtasn1.h)
("asn1_parser2array" libtasn1.h)
("asn1_parser2tree" libtasn1.h)
("asn1_perror" libtasn1.h)
("asn1_print_structure" libtasn1.h)
("asn1_read_tag" libtasn1.h)
("asn1_read_value" libtasn1.h)
("asn1_strerror" libtasn1.h)
("asn1_write_value" libtasn1.h)
("asprintf" stdio.h)
("assert" assert.h)
("assert_perror" assert.h)
("at_quick_exit" stdlib.h)
("atan" math.h)
("atan2" math.h)
("atan2f" math.h)
("atan2l" math.h)
("atanf" math.h)
("atanh" math.h)
("atanhf" math.h)
("atanhl" math.h)
("atanl" math.h)
("atexit" stdlib.h)
("atof" stdlib.h)
("atoi" stdlib.h)
("atol" stdlib.h)
("atoll" stdlib.h)
("atomic_bool" stdatomic.h)
("atomic_char" stdatomic.h)
("atomic_char16_t" stdatomic.h)
("atomic_char32_t" stdatomic.h)
("atomic_compare_exchange_strong" stdatomic.h)
("atomic_compare_exchange_strong_explicit" stdatomic.h)
("atomic_compare_exchange_weak" stdatomic.h)
("atomic_compare_exchange_weak_explicit" stdatomic.h)
("atomic_exchange" stdatomic.h)
("atomic_exchange_explicit" stdatomic.h)
("atomic_fetch_add" stdatomic.h)
("atomic_fetch_add_explicit" stdatomic.h)
("atomic_fetch_and" stdatomic.h)
("atomic_fetch_and_explicit" stdatomic.h)
("atomic_fetch_or" stdatomic.h)
("atomic_fetch_or_explicit" stdatomic.h)
("atomic_fetch_xor" stdatomic.h)
("atomic_fetch_xor_explicit" stdatomic.h)
("atomic_flag" stdatomic.h)
("atomic_init" stdatomic.h)
("atomic_int" stdatomic.h)
("atomic_int_fast16_t" stdatomic.h)
("atomic_int_fast32_t" stdatomic.h)
("atomic_int_fast64_t" stdatomic.h)
("atomic_int_fast8_t" stdatomic.h)
("atomic_int_least16_t" stdatomic.h)
("atomic_int_least32_t" stdatomic.h)
("atomic_int_least64_t" stdatomic.h)
("atomic_int_least8_t" stdatomic.h)
("atomic_intmax_t" stdatomic.h)
("atomic_intprt_t" stdatomic.h)
("atomic_is_lock_free" stdatomic.h)
("atomic_llong" stdatomic.h)
("atomic_long" stdatomic.h)
("atomic_ptrdiff_t" stdatomic.h)
("atomic_schar" stdatomic.h)
("atomic_short" stdatomic.h)
("atomic_signal_fence" stdatomic.h)
("atomic_size_t" stdatomic.h)
("atomic_store" stdatomic.h)
("atomic_store_explicit" stdatomic.h)
("atomic_uchar" stdatomic.h)
("atomic_uint" stdatomic.h)
("atomic_uint_fast16_t" stdatomic.h)
("atomic_uint_fast32_t" stdatomic.h)
("atomic_uint_fast64_t" stdatomic.h)
("atomic_uint_fast8_t" stdatomic.h)
("atomic_uint_least16_t" stdatomic.h)
("atomic_uint_least32_t" stdatomic.h)
("atomic_uint_least64_t" stdatomic.h)
("atomic_uint_least8_t" stdatomic.h)
("atomic_uintmax_t" stdatomic.h)
("atomic_uintprt_t" stdatomic.h)
("atomic_ullong" stdatomic.h)
("atomic_ulong" stdatomic.h)
("atomic_ushort" stdatomic.h)
("atomic_wchar_t" stdatomic.h)
("atoq" stdlib.h)
("basename" libgen.h)
("bcmp" strings.h)
("bcopy" strings.h)
("bdflush" sys/kdaemon.h)
("be16toh" endian.h)
("be32toh" endian.h)
("be64toh" endian.h)
("bind" sys/socket.h sys/types.h)
("bindresvport" sys/types.h netinet/in.h)
("brk" unistd.h)
("bsd_signal" signal.h)
("bsearch" stdlib.h)
("btowc" wchar.h)
("bzero" strings.h)
("c16rtomb" uchar.h)
("c32rtomb" uchar.h)
("cabs" complex.h)
("cabsf" complex.h)
("cabsl" complex.h)
("cacheflush" asm/cachectl.h)
("cacos" complex.h)
("cacosf" complex.h)
("cacosh" complex.h)
("cacoshf" complex.h)
("cacoshl" complex.h)
("cacosl" complex.h)
("call_once" threads.h)
("calloc" stdlib.h)
("canonicalize_file_name" stdlib.h)
("capget" sys/capability.h)
("capset" sys/capability.h)
("carg" complex.h)
("cargf" complex.h)
("cargl" complex.h)
("casin" complex.h)
("casinf" complex.h)
("casinh" complex.h)
("casinhf" complex.h)
("casinhl" complex.h)
("casinl" complex.h)
("catan" complex.h)
("catanf" complex.h)
("catanh" complex.h)
("catanhf" complex.h)
("catanhl" complex.h)
("catanl" complex.h)
("catclose" nl_types.h)
("catgets" nl_types.h)
("catopen" nl_types.h)
("cbc_crypt" rpc/des_crypt.h)
("cbrt" math.h)
("cbrtf" math.h)
("cbrtl" math.h)
("ccos" complex.h)
("ccosf" complex.h)
("ccosh" complex.h)
("ccoshf" complex.h)
("ccoshl" complex.h)
("ccosl" complex.h)
("ceil" math.h)
("ceilf" math.h)
("ceill" math.h)
("cerf" complex.h)
("cerfc" complex.h)
("cerfcf" complex.h)
("cerfcl" complex.h)
("cerff" complex.h)
("cerfl" complex.h)
("cexp" complex.h)
("cexp2" complex.h)
("cexp2f" complex.h)
("cexp2l" complex.h)
("cexpf" complex.h)
("cexpl" complex.h)
("cfgetispeed" unistd.h termios.h)
("cfgetospeed" unistd.h termios.h)
("cfmakeraw" unistd.h termios.h)
("cfree" stdlib.h)
("cfsetispeed" unistd.h termios.h)
("cfsetospeed" unistd.h termios.h)
("cfsetspeed" unistd.h termios.h)
("chdir" unistd.h)
("chmod" sys/stat.h)
("chown" unistd.h)
("chroot" unistd.h)
("cimag" complex.h)
("cimagf" complex.h)
("cimagl" complex.h)
("clearenv" stdlib.h)
("clearerr" stdio.h)
("clearerr_unlocked" stdio.h)
("clock_getcpuclockid" time.h)
("clock_getres" time.h)
("clock_gettime" time.h)
("clock_nanosleep" time.h)
("clock_settime" time.h)
("clock_t" time.h)
("clog" complex.h)
("clog10" complex.h)
("clog10f" complex.h)
("clog10l" complex.h)
("clog2" complex.h)
("clog2f" complex.h)
("clog2l" complex.h)
("clogf" complex.h)
("clogl" complex.h)
("clone" sched.h)
("close" unistd.h)
("closedir" sys/types.h dirent.h)
("closelog" syslog.h)
("cnd_broadcast" threads.h)
("cnd_init" threads.h)
("cnd_t" threads.h)
("cnd_timedwait" threads.h)
("cnd_wait" threads.h)
("confstr" unistd.h)
("conj" complex.h)
("conjf" complex.h)
("conjl" complex.h)
("connect" sys/socket.h sys/types.h)
("copysign" math.h)
("copysignf" math.h)
("copysignl" math.h)
("cos" math.h)
("cosf" math.h)
("cosh" math.h)
("coshf" math.h)
("coshl" math.h)
("cosl" math.h)
("cpow" complex.h)
("cpowf" complex.h)
("cpowl" complex.h)
("cproj" complex.h)
("cprojf" complex.h)
("cprojl" complex.h)
("creal" complex.h)
("crealf" complex.h)
("creall" complex.h)
("creat" sys/stat.h sys/types.h fcntl.h)
("create_module" linux/module.h)
("crypt" unistd.h)
("crypt_r" crypt.h unistd.h)
("csin" complex.h)
("csinf" complex.h)
("csinh" complex.h)
("csinhf" complex.h)
("csinhl" complex.h)
("csinl" complex.h)
("csqrt" complex.h)
("csqrtf" complex.h)
("csqrtl" complex.h)
("ctan" complex.h)
("ctanf" complex.h)
("ctanh" complex.h)
("ctanhf" complex.h)
("ctanhl" complex.h)
("ctanl" complex.h)
("ctermid" stdio.h)
("ctime" time.h)
("ctime_r" time.h)
("cuserid" unistd.h stdio.h)
("daemon" unistd.h)
("dbopen" db.h sys/types.h limits.h fcntl.h)
("delete_module" linux/module.h)
("des_setparity" rpc/des_crypt.h)
("difftime" time.h)
("dirfd" sys/types.h dirent.h)
("dirname" libgen.h)
("div" stdlib.h)
("dlclose" dlfcn.h)
("dlerror" dlfcn.h)
("dlopen" dlfcn.h)
("dlsym" dlfcn.h)
("dn_comp" arpa/nameser.h netinet/in.h resolv.h)
("dn_expand" arpa/nameser.h netinet/in.h resolv.h)
("dprintf" stdio.h)
("drand48_r" stdlib.h)
("drem" math.h)
("dremf" math.h)
("dreml" math.h)
("dysize" time.h)
("eaccess" unistd.h)
("ecb_crypt" rpc/des_crypt.h)
("ecvt" stdlib.h)
("ecvt_r" stdlib.h)
("encrypt" unistd.h)
("encrypt_r" crypt.h stdlib.h unistd.h)
("endaliasent" aliases.h)
("endfsent" fstab.h)
("endmntent" mntent.h stdio.h)
("endnetgrent" netdb.h)
("endrpcent" netdb.h)
("endttyent" ttyent.h)
("envz_add" envz.h)
("envz_entry" envz.h)
("envz_get" envz.h)
("envz_merge" envz.h)
("envz_remove" envz.h)
("envz_strip" envz.h)
("epoll_create" sys/epoll.h)
("epoll_create1" sys/epoll.h)
("epoll_ctl" sys/epoll.h)
("epoll_pwait" sys/epoll.h)
("epoll_wait" sys/epoll.h)
("erand48" stdlib.h)
("erand48_r" stdlib.h)
("erf" math.h)
("erfc" math.h)
("erfcf" math.h)
("erfcl" math.h)
("erff" math.h)
("erfl" math.h)
("err" err.h)
("errno" errno.h)
("errx" err.h)
("ether_aton" netinet/ether.h)
("ether_aton_r" netinet/ether.h)
("ether_hostton" netinet/ether.h)
("ether_line" netinet/ether.h)
("ether_ntoa" netinet/ether.h)
("ether_ntoa_r" netinet/ether.h)
("ether_ntohost" netinet/ether.h)
("euidaccess" unistd.h)
("eventfd" sys/eventfd.h)
("execl" unistd.h)
("execle" unistd.h)
("execlp" unistd.h)
("execv" unistd.h)
("execve" unistd.h)
("execvp" unistd.h)
("execvpe" unistd.h)
("exit" stdlib.h)
("exit_group" linux/unistd.h)
("exp" math.h)
("exp10" math.h)
("exp10f" math.h)
("exp10l" math.h)
("exp2" math.h)
("exp2f" math.h)
("exp2l" math.h)
("expf" math.h)
("expl" math.h)
("expm1" math.h)
("expm1f" math.h)
("expm1l" math.h)
("fabs" math.h)
("fabsf" math.h)
("fabsl" math.h)
("faccessat" unistd.h fcntl.h)
("fallocate" fcntl.h)
("fchdir" unistd.h)
("fchmod" sys/stat.h)
("fchmodat" sys/stat.h fcntl.h)
("fchown" unistd.h)
("fchownat" unistd.h fcntl.h)
("fclose" stdio.h)
("fcntl" unistd.h fcntl.h)
("fcvt" stdlib.h)
("fcvt_r" stdlib.h)
("fdatasync" unistd.h)
("fdim" math.h)
("fdimf" math.h)
("fdiml" math.h)
("fdopen" stdio.h)
("fdopendir" sys/types.h dirent.h)
("feclearexcept" fenv.h)
("fegetenv" fenv.h)
("fegetexceptflag" fenv.h)
("fegetround" fenv.h)
("feholdexcept" fenv.h)
("feof" stdio.h)
("feof_unlocked" stdio.h)
("feraiseexcept" fenv.h)
("ferror" stdio.h)
("ferror_unlocked" stdio.h)
("fesetenv" fenv.h)
("fesetexceptflag" fenv.h)
("fesetround" fenv.h)
("fetestexcept" fenv.h)
("feupdateenv" fenv.h)
("fexecve" unistd.h)
("fflush" stdio.h)
("fflush_unlocked" stdio.h)
("ffs" strings.h)
("ffsl" strings.h string.h)
("ffsll" strings.h string.h)
("fgetc" stdio.h)
("fgetc_unlocked" stdio.h)
("fgetgrent" sys/types.h stdio.h grp.h)
("fgetgrent_r" grp.h)
("fgetpos" stdio.h)
("fgetpwent" pwd.h sys/types.h stdio.h)
("fgetpwent_r" pwd.h)
("fgets" stdio.h)
("fgets_unlocked" stdio.h)
("fgetspent" shadow.h)
("fgetspent_r" shadow.h)
("fgetss" wchar.h)
("fgetwc" wchar.h)
("fgetwc_unlocked" stdio.h wchar.h)
("fgetws" wchar.h)
("fgetws_unlocked" stdio.h wchar.h)
("fileno" stdio.h)
("fileno_unlocked" stdio.h)
("finite" math.h)
("finitef" math.h)
("finitel" math.h)
("flock" sys/file.h)
("flockfile" stdio.h)
("floor" math.h)
("floorf" math.h)
("floorl" math.h)
("fma" math.h)
("fmaf" math.h)
("fmal" math.h)
("fmax" math.h)
("fmaxf" math.h)
("fmaxl" math.h)
("fmemopen" stdio.h)
("fmin" math.h)
("fminf" math.h)
("fminl" math.h)
("fmod" math.h)
("fmodf" math.h)
("fmodl" math.h)
("fmtmsg" fmtmsg.h)
("fnmatch" fnmatch.h)
("fopen" stdio.h)
("fopencookie" stdio.h)
("forkpty" pty.h)
("fpathconf" unistd.h)
("fpclassify" math.h)
("fpos_t" stdio.h)
("fprintf" stdio.h)
("fpurge" stdio.h)
("fputc" stdio.h)
("fputc_unlocked" stdio.h)
("fputs" stdio.h)
("fputs_unlocked" stdio.h)
("fputwc" wchar.h)
("fputwc_unlocked" stdio.h wchar.h)
("fputws" wchar.h)
("fputws_unlocked" stdio.h wchar.h)
("fread" stdio.h)
("fread_unlocked" stdio.h)
("free" stdlib.h)
("freeaddrinfo" sys/socket.h sys/types.h netdb.h)
("freehostent" sys/socket.h sys/types.h netdb.h)
("freeifaddrs" sys/types.h ifaddrs.h)
("freopen" stdio.h)
("frexp" math.h)
("frexpf" math.h)
("frexpl" math.h)
("fscanf" stdio.h)
("fseek" stdio.h)
("fseeko" stdio.h)
("fsetpos" stdio.h)
("fstat" sys/stat.h unistd.h sys/types.h)
("fstatat" sys/stat.h fcntl.h)
("fstatfs" sys/vfs.h)
("fstatvfs" sys/statvfs.h)
("fsync" unistd.h)
("ftell" stdio.h)
("ftello" stdio.h)
("ftime" sys/timeb.h)
("ftok" sys/ipc.h sys/types.h)
("ftruncate" unistd.h sys/types.h)
("ftrylockfile" stdio.h)
("fts_children" sys/stat.h fts.h sys/types.h)
("fts_close" sys/stat.h fts.h sys/types.h)
("fts_open" sys/stat.h fts.h sys/types.h)
("fts_read" sys/stat.h fts.h sys/types.h)
("fts_set" sys/stat.h fts.h sys/types.h)
("ftw" ftw.h)
("funlockfile" stdio.h)
("futex" linux/futex.h sys/time.h)
("futimens" sys/stat.h)
("futimes" sys/time.h)
("futimesat" fcntl.h)
("fwide" wchar.h)
("fwprintf" wchar.h)
("fwrite" stdio.h)
("fwrite_unlocked" stdio.h)
("gai_cancel" netdb.h)
("gai_error" netdb.h)
("gai_strerror" sys/socket.h sys/types.h netdb.h)
("gai_suspend" netdb.h)
("gamma" math.h)
("gammaf" math.h)
("gammal" math.h)
("gcvt" stdlib.h)
("get_current_dir_name" unistd.h)
("get_kernel_syms" linux/module.h)
("get_mempolicy" numaif.h)
("get_thread_area" linux/unistd.h asm/ldt.h)
("getaddrinfo" sys/socket.h sys/types.h netdb.h)
("getaddrinfo_a" netdb.h)
("getaliasbyname" aliases.h)
("getaliasbyname_r" aliases.h)
("getaliasent" aliases.h)
("getaliasent_r" aliases.h)
("getc" stdio.h)
("getc_unlocked" stdio.h)
("getchar" stdio.h)
("getchar_unlocked" stdio.h)
("getcontext" ucontext.h)
("getcpu" linux/getcpu.h)
("getcwd" unistd.h)
("getdate" time.h)
("getdate_r" time.h)
("getdelim" stdio.h)
("getdirentries" dirent.h)
("getdomainname" unistd.h)
("getenv" stdlib.h)
("getfsent" fstab.h)
("getfsfile" fstab.h)
("getfsspec" fstab.h)
("getgrent_r" grp.h)
("getgrgid" sys/types.h grp.h)
("getgrgid_r" sys/types.h grp.h)
("getgrnam" sys/types.h grp.h)
("getgrnam_r" sys/types.h grp.h)
("getgrouplist" grp.h)
("gethostbyaddr" sys/socket.h netdb.h)
("gethostbyaddr_r" sys/socket.h netdb.h)
("gethostbyname" netdb.h)
("gethostbyname2" sys/socket.h netdb.h)
("gethostbyname2_r" sys/socket.h netdb.h)
("gethostbyname_r" sys/socket.h netdb.h)
("gethostent_r" sys/socket.h netdb.h)
("gethostname" unistd.h)
("getifaddrs" sys/types.h ifaddrs.h)
("getipnodebyaddr" sys/socket.h sys/types.h netdb.h)
("getipnodebyname" sys/socket.h sys/types.h netdb.h)
("getitimer" sys/time.h)
("getline" stdio.h)
("getloadavg" stdlib.h)
("getlogin" unistd.h)
("getlogin_r" unistd.h)
("getmntent" mntent.h stdio.h)
("getmntent_r" mntent.h stdio.h)
("getnameinfo" sys/socket.h netdb.h)
("getnetbyaddr" netdb.h)
("getnetbyaddr_r" netdb.h)
("getnetbyname" netdb.h)
("getnetbyname_r" netdb.h)
("getnetent_r" netdb.h)
("getnetgrent" netdb.h)
("getnetgrent_r" netdb.h)
("getopt" unistd.h)
("getopt_long" getopt.h unistd.h)
("getopt_long_only" getopt.h unistd.h)
("getpass" unistd.h)
("getpeername" sys/socket.h)
("getpgid" unistd.h)
("getpgrp" unistd.h)
("getpriority" sys/resource.h sys/time.h)
("getprotobyname" netdb.h)
("getprotobyname_r" netdb.h)
("getprotobynumber" netdb.h)
("getprotobynumber_r" netdb.h)
("getprotoent_r" netdb.h)
("getpt" stdlib.h)
("getpw" pwd.h sys/types.h)
("getpwent_r" pwd.h)
("getpwnam" pwd.h sys/types.h)
("getpwnam_r" pwd.h sys/types.h)
("getpwuid" pwd.h sys/types.h)
("getpwuid_r" pwd.h sys/types.h)
("getresgid" unistd.h)
("getresuid" unistd.h)
("getrlimit" sys/resource.h sys/time.h)
("getrpcbyname" netdb.h)
("getrpcbyname_r" netdb.h)
("getrpcbynumber" netdb.h)
("getrpcbynumber_r" netdb.h)
("getrpcent" netdb.h)
("getrpcent_r" netdb.h)
("getrusage" sys/resource.h sys/time.h)
("gets" stdio.h)
("getservbyname" netdb.h)
("getservbyname_r" netdb.h)
("getservbyport" netdb.h)
("getservbyport_r" netdb.h)
("getservent_r" netdb.h)
("getsid" unistd.h)
("getsockname" sys/socket.h)
("getsockopt" sys/socket.h sys/types.h)
("getspent_r" shadow.h)
("getspnam" shadow.h)
("getspnam_r" shadow.h)
("getsubopt" stdlib.h)
("gettimeofday" sys/time.h)
("getttyent" ttyent.h)
("getttynam" ttyent.h)
("getumask" sys/stat.h sys/types.h)
("getutid" utmp.h)
("getutline" utmp.h)
("getutmp" utmpx.h)
("getutmpx" utmpx.h)
("getw" stdio.h)
("getwc" stdio.h wchar.h)
("getwc_unlocked" stdio.h wchar.h)
("getwchar" wchar.h)
("getwchar_unlocked" stdio.h wchar.h)
("getwd" unistd.h)
("glob" glob.h)
("globfree" glob.h)
("gmtime" time.h)
("gmtime_r" time.h)
("grantpt" stdlib.h)
("gsignal" signal.h)
("hasmntopt" mntent.h stdio.h)
("hcreate" search.h)
("hcreate_r" search.h)
("hdestroy" search.h)
("hdestroy_r" search.h)
("herror" sys/socket.h netdb.h)
("hsearch" search.h)
("hsearch_r" search.h)
("hstrerror" sys/socket.h netdb.h)
("htobe16" endian.h)
("htobe32" endian.h)
("htobe64" endian.h)
("htole16" endian.h)
("htole32" endian.h)
("htole64" endian.h)
("htonl" arpa/inet.h)
("htons" arpa/inet.h)
("hypot" math.h)
("hypotf" math.h)
("hypotl" math.h)
("iconv" iconv.h)
("iconv_close" iconv.h)
("iconv_open" iconv.h)
("ilogb" math.h)
("ilogbf" math.h)
("ilogbl" math.h)
("imaxabs" stdlib.h inttypes.h)
("imaxdiv" stdlib.h inttypes.h)
("index" strings.h)
("inet_addr" arpa/inet.h sys/socket.h netinet/in.h)
("inet_aton" arpa/inet.h sys/socket.h netinet/in.h)
("inet_lnaof" arpa/inet.h sys/socket.h netinet/in.h)
("inet_makeaddr" arpa/inet.h sys/socket.h netinet/in.h)
("inet_netof" arpa/inet.h sys/socket.h netinet/in.h)
("inet_network" arpa/inet.h sys/socket.h netinet/in.h)
("inet_ntoa" arpa/inet.h sys/socket.h netinet/in.h)
("inet_ntop" arpa/inet.h)
("inet_pton" arpa/inet.h)
("init_module" linux/module.h)
("initgroups" sys/types.h grp.h)
("initstate" stdlib.h)
("initstate_r" stdlib.h)
("innetgr" netdb.h)
("inotify_add_watch" sys/inotify.h)
("inotify_init" sys/inotify.h)
("inotify_init1" sys/inotify.h)
("inotify_rm_watch" sys/inotify.h)
("insque" search.h)
("int" search.h)
("int16_t" stdint.h)
("int32_t" stdint.h)
("int64_t" stdint.h)
("int8_t" stdint.h)
("int_fast16_t" stdint.h)
("int_fast32_t" stdint.h)
("int_fast64_t" stdint.h)
("int_fast8_t" stdint.h)
("int_least16_t" stdint.h)
("int_least32_t" stdint.h)
("int_least64_t" stdint.h)
("int_least8_t" stdint.h)
("intmax_t" stdint.h)
("intptr_t" stdint.h)
("io_cancel" libaio.h)
("io_destroy" libaio.h)
("io_getevents" linux/time.h libaio.h)
("io_setup" libaio.h)
("io_submit" libaio.h)
("ioctl" sys/ioctl.h)
("ioperm" unistd.h sys/io.h)
("iopl" sys/io.h)
("iruserok" netdb.h)
("isalnum" ctype.h)
("isalpha" ctype.h)
("isascii" ctype.h)
("isatty" unistd.h)
("isblank" ctype.h)
("iscntrl" ctype.h)
("isdigit" ctype.h)
("isfinite" math.h)
("isgraph" ctype.h)
("isgreater" math.h)
("isgreaterequal" math.h)
("isinf" math.h)
("isinff" math.h)
("isinfl" math.h)
("isless" math.h)
("islessequal" math.h)
("islessgreater" math.h)
("islower" ctype.h)
("isnan" math.h)
("isnanf" math.h)
("isnanl" math.h)
("isnormal" math.h)
("isprint" cctype)
("ispunct" ctype.h)
("isspace" ctype.h)
("isunordered" math.h)
("isupper" ctype.h)
("iswalnum" wctype.h)
("iswalpha" wctype.h)
("iswblank" wctype.h)
("iswcntrl" wctype.h)
("iswctype" wctype.h)
("iswdigit" wctype.h)
("iswgraph" wctype.h)
("iswlower" wctype.h)
("iswprint" wctype.h)
("iswpunct" wctype.h)
("iswspace" wctype.h)
("iswupper" wctype.h)
("iswxdigit" wctype.h)
("isxdigit" ctype.h)
("j0" math.h)
("j0f" math.h)
("j0l" math.h)
("j1" math.h)
("j1f" math.h)
("j1l" math.h)
("jmp_buf" setjmp.h)
("jn" math.h)
("jnf" math.h)
("jnl" math.h)
("jrand48" stdlib.h)
("jrand48_r" stdlib.h)
("kexec_load" linux/kexec.h)
("key_decryptsession" rpc/rpc.h)
("key_encryptsession" rpc/rpc.h)
("key_gendes" rpc/rpc.h)
("key_secretkey_is_set" rpc/rpc.h)
("key_setsecret" rpc/rpc.h)
("keyctl" keyutils.h)
("kill" sys/types.h signal.h)
("kill_dependency" stdatomic.h)
("killpg" signal.h)
("klogctl" sys/klog.h)
("l64a" stdlib.h)
("labs" stdlib.h)
("lchown" unistd.h)
("lcong48" stdlib.h)
("lcong48_r" stdlib.h)
("lconv" locale.h)
("ldexp" math.h)
("ldexpf" math.h)
("ldexpl" math.h)
("ldiv" stdlib.h)
("le16toh" endian.h)
("le32toh" endian.h)
("le64toh" endian.h)
("lfind" search.h)
("lgamma" math.h)
("lgamma_r" math.h)
("lgammaf" math.h)
("lgammaf_r" math.h)
("lgammal" math.h)
("lgammal_r" math.h)
("libtasn1_perror" libtasn1.h)
("libtasn1_strerror" libtasn1.h)
("link" unistd.h)
("linkat" unistd.h fcntl.h)
("lio_listio" aio.h)
("listen" sys/socket.h sys/types.h)
("llabs" stdlib.h)
("lldiv" stdlib.h)
("llrint" math.h)
("llrintf" math.h)
("llrintl" math.h)
("llround" math.h)
("llroundf" math.h)
("llroundl" math.h)
("localeconv" locale.h)
("localtime" time.h)
("localtime_r" time.h)
("lockf" unistd.h)
("log" math.h)
("log10" math.h)
("log10f" math.h)
("log10l" math.h)
("log1p" math.h)
("log1pf" math.h)
("log1pl" math.h)
("log2" math.h)
("log2f" math.h)
("log2l" math.h)
("logb" math.h)
("logbf" math.h)
("logbl" math.h)
("logf" math.h)
("login" utmp.h)
("login_tty" utmp.h pty.h)
("logl" math.h)
("logout" utmp.h)
("logwtmp" utmp.h)
("longjmp" setjmp.h)
("lrand48_r" stdlib.h)
("lrint" math.h)
("lrintf" math.h)
("lrintl" math.h)
("lround" math.h)
("lroundf" math.h)
("lroundl" math.h)
("lsearch" search.h)
("lseek" unistd.h sys/types.h)
("lseek64" unistd.h sys/types.h)
("lstat" sys/stat.h unistd.h sys/types.h)
("lutimes" sys/time.h)
("madvise" sys/mman.h)
("major" sys/types.h)
("makecontext" ucontext.h)
("makedev" sys/types.h)
("malloc" stdlib.h)
("matherr" math.h)
("mbind" numaif.h)
("mblen" stdlib.h)
("mbrlen" wchar.h)
("mbrtoc16" uchar.h)
("mbrtoc32" cuchar)
("mbrtowc" wchar.h)
("mbsinit" wchar.h)
("mbsnrtowcs" wchar.h)
("mbsrtowcs" wchar.h)
("mbstate_t" wchar.h)
("mbstowcs" stdlib.h)
("mbtowc" stdlib.h)
("memalign" stdlib.h malloc.h)
("memccpy" string.h)
("memchr" string.h)
("memcmp" string.h)
("memcpy" string.h)
("memfrob" string.h)
("memmem" string.h)
("memmove" string.h)
("mempcpy" string.h)
("memrchr" string.h)
("memset" string.h)
("migrate_pages" numaif.h)
("mincore" sys/mman.h unistd.h)
("minor" sys/types.h)
("mkdir" sys/stat.h sys/types.h)
("mkdirat" sys/stat.h fcntl.h)
("mkdtemp" stdlib.h)
("mkfifo" sys/stat.h sys/types.h)
("mkfifoat" sys/stat.h fcntl.h)
("mknod" sys/stat.h sys/types.h unistd.h fcntl.h)
("mknodat" sys/stat.h fcntl.h)
("mkostemp" stdlib.h)
("mkostemps" stdlib.h)
("mkstemp" stdlib.h)
("mkstemps" stdlib.h)
("mktemp" stdlib.h)
("mktime" time.h)
("mlock" sys/mman.h)
("mlockall" sys/mman.h)
("mmap" sys/mman.h)
("mmap2" sys/mman.h)
("modf" math.h)
("modff" math.h)
("modfl" math.h)
("modify_ldt" sys/types.h)
("mount" sys/mount.h)
("move_pages" numaif.h)
("mpool_close" db.h mpool.h)
("mpool_filter" db.h mpool.h)
("mpool_get" db.h mpool.h)
("mpool_new" db.h mpool.h)
("mpool_open" db.h mpool.h)
("mpool_put" db.h mpool.h)
("mpool_sync" db.h mpool.h)
("mprotect" sys/mman.h)
("mq_close" mqueue.h)
("mq_getattr" mqueue.h)
("mq_getsetattr" mqueue.h sys/types.h)
("mq_notify" mqueue.h)
("mq_open" sys/stat.h mqueue.h fcntl.h)
("mq_receive" mqueue.h)
("mq_send" mqueue.h)
("mq_setattr" mqueue.h)
("mq_timedreceive" mqueue.h time.h)
("mq_timedsend" mqueue.h time.h)
("mq_unlink" mqueue.h)
("mrand48_r" stdlib.h)
("mremap" sys/mman.h)
("msgctl" sys/msg.h sys/ipc.h sys/types.h)
("msgget" sys/msg.h sys/ipc.h sys/types.h)
("msgrcv" sys/msg.h sys/ipc.h sys/types.h)
("msgsnd" sys/msg.h sys/ipc.h sys/types.h)
("msync" sys/mman.h)
("mtrace" mcheck.h)
("mtx_destroy" threads.h)
("mtx_init" threads.h)
("mtx_lock" threads.h)
("mtx_t" threads.h)
("mtx_trylock" threads.h)
("mtx_unlock" threads.h)
("munlock" sys/mman.h)
("munmap" sys/mman.h)
("muntrace" mcheck.h)
("nan" math.h)
("nanf" math.h)
("nanl" math.h)
("nanosleep" time.h)
("nearbyint" math.h)
("nearbyintf" math.h)
("nearbyintl" math.h)
("nextafter" math.h)
("nextafterf" math.h)
("nextafterl" math.h)
("nexttoward" math.h)
("nexttowardf" math.h)
("nexttowardl" math.h)
("nfsservctl" linux/nfsd/syscall.h)
("nftw" ftw.h)
("nice" unistd.h)
("nl_langinfo" langinfo.h)
("nrand48" stdlib.h)
("nrand48_r" stdlib.h)
("ntohl" arpa/inet.h)
("ntohs" arpa/inet.h)
("offsetof" stddef.h)
("on_exit" stdlib.h)
("once_flag" threads.h)
("open" sys/stat.h sys/types.h fcntl.h)
("open_memstream" stdio.h)
("open_wmemstream" stdio.h wchar.h)
("openat" fcntl.h)
("opendir" sys/types.h dirent.h)
("openlog" syslog.h)
("openpty" pty.h)
("passwd2des" rpc/des_crypt.h)
("pathconf" unistd.h)
("pciconfig_iobase" pci.h)
("pciconfig_read" pci.h)
("pciconfig_write" pci.h)
("pclose" stdio.h)
("perror" stdio.h)
("personality" sys/personality.h)
("poll" poll.h)
("popen" stdio.h)
("posix_fadvise" fcntl.h)
("posix_fallocate" fcntl.h)
("posix_memalign" stdlib.h)
("posix_openpt" stdlib.h fcntl.h)
("pow" math.h)
("pow10" math.h)
("pow10f" math.h)
("pow10l" math.h)
("powf" math.h)
("powl" math.h)
("ppoll" poll.h)
("prctl" sys/prctl.h)
("pread" unistd.h)
("preadv" sys/uio.h)
("printf" stdio.h)
("prlimit" sys/resource.h sys/time.h)
("profil" unistd.h)
("pselect" sys/select.h unistd.h sys/types.h sys/time.h)
("psiginfo" signal.h)
("psignal" signal.h)
("pthread_attr_destroy" pthread.h)
("pthread_attr_getaffinity_np" pthread.h)
("pthread_attr_getdetachstate" pthread.h)
("pthread_attr_getguardsize" pthread.h)
("pthread_attr_getinheritsched" pthread.h)
("pthread_attr_getschedparam" pthread.h)
("pthread_attr_getschedpolicy" pthread.h)
("pthread_attr_getscope" pthread.h)
("pthread_attr_getstack" pthread.h)
("pthread_attr_getstackaddr" pthread.h)
("pthread_attr_getstacksize" pthread.h)
("pthread_attr_init" pthread.h)
("pthread_attr_setaffinity_np" pthread.h)
("pthread_attr_setdetachstate" pthread.h)
("pthread_attr_setguardsize" pthread.h)
("pthread_attr_setinheritsched" pthread.h)
("pthread_attr_setschedparam" pthread.h)
("pthread_attr_setschedpolicy" pthread.h)
("pthread_attr_setscope" pthread.h)
("pthread_attr_setstack" pthread.h)
("pthread_attr_setstackaddr" pthread.h)
("pthread_attr_setstacksize" pthread.h)
("pthread_cancel" pthread.h)
("pthread_cleanup_pop" pthread.h)
("pthread_cleanup_pop_restore_np" pthread.h)
("pthread_cleanup_push" pthread.h)
("pthread_cleanup_push_defer_np" pthread.h)
("pthread_create" pthread.h)
("pthread_detach" pthread.h)
("pthread_equal" pthread.h)
("pthread_exit" pthread.h)
("pthread_getaffinity_np" pthread.h)
("pthread_getattr_np" pthread.h)
("pthread_getconcurrency" pthread.h)
("pthread_getcpuclockid" pthread.h time.h)
("pthread_join" pthread.h)
("pthread_kill" signal.h)
("pthread_setaffinity_np" pthread.h)
("pthread_setcancelstate" pthread.h)
("pthread_setcanceltype" pthread.h)
("pthread_setconcurrency" pthread.h)
("pthread_sigmask" signal.h)
("pthread_sigqueue" pthread.h)
("pthread_timedjoin_np" pthread.h)
("pthread_tryjoin_np" pthread.h)
("ptrace" sys/ptrace.h)
("ptsname" stdlib.h)
("ptsname_r" stdlib.h)
("putc" stdio.h)
("putc_unlocked" stdio.h)
("putchar" stdio.h)
("putchar_unlocked" stdio.h)
("putenv" stdlib.h)
("putgrent" grp.h)
("putpwent" pwd.h sys/types.h stdio.h)
("puts" stdio.h)
("putspent" shadow.h)
("pututline" utmp.h)
("putw" stdio.h)
("putwc" stdio.h wchar.h)
("putwc_unlocked" stdio.h wchar.h)
("putwchar" wchar.h)
("putwchar_unlocked" stdio.h wchar.h)
("pwrite" unistd.h)
("pwritev" sys/uio.h)
("qecvt" stdlib.h)
("qecvt_r" stdlib.h)
("qfcvt" stdlib.h)
("qfcvt_r" stdlib.h)
("qgcvt" stdlib.h)
("qsort" stdlib.h)
("quick_exit" stdlib.h)
("quotactl" xfs/xqm.h sys/quota.h)
("raise" signal.h)
("rand_r" stdlib.h)
("random_r" stdlib.h)
("rawmemchr" string.h)
("rcmd" netdb.h)
("re_comp" sys/types.h regex.h)
("re_exec" sys/types.h regex.h)
("read" unistd.h)
("readahead" fcntl.h)
("readdir" dirent.h)
("readdir_r" dirent.h)
("readlink" unistd.h)
("readlinkat" unistd.h fcntl.h)
("readv" sys/uio.h)
("realloc" stdlib.h)
("realpath" limits.h stdlib.h)
("reboot" unistd.h linux/reboot.h)
("recv" sys/socket.h sys/types.h)
("recvfrom" sys/socket.h sys/types.h)
("recvmsg" sys/socket.h sys/types.h)
("regcomp" sys/types.h regex.h)
("regerror" sys/types.h regex.h)
("regexec" sys/types.h regex.h)
("regfree" sys/types.h regex.h)
("remainder" math.h)
("remainderf" math.h)
("remainderl" math.h)
("remap_file_pages" sys/mman.h)
("remove" stdio.h)
("remque" search.h)
("remquo" math.h)
("remquof" math.h)
("remquol" math.h)
("rename" stdio.h)
("renameat" fcntl.h stdio.h)
("request_key" keyutils.h)
("res_mkquery" arpa/nameser.h netinet/in.h resolv.h)
("res_query" arpa/nameser.h netinet/in.h resolv.h)
("res_querydomain" arpa/nameser.h netinet/in.h resolv.h)
("res_search" arpa/nameser.h netinet/in.h resolv.h)
("res_send" arpa/nameser.h netinet/in.h resolv.h)
("rewind" stdio.h)
("rewinddir" sys/types.h dirent.h)
("rexec" netdb.h)
("rindex" strings.h)
("rint" math.h)
("rintf" math.h)
("rintl" math.h)
("rmdir" unistd.h)
("round" math.h)
("roundf" math.h)
("roundl" math.h)
("rpmatch" stdlib.h)
("rresvport" netdb.h)
("rtime" rpc/des_crypt.h)
("ruserok" netdb.h)
("sbrk" unistd.h)
("scalb" math.h)
("scalbf" math.h)
("scalbl" math.h)
("scalbln" cmath)
("scalblnf" math.h)
("scalblnl" math.h)
("scalbn" cmath)
("scalbnf" math.h)
("scalbnl" math.h)
("scandir" dirent.h)
("scanf" stdio.h)
("sched_get_priority_max" sched.h)
("sched_get_priority_min" sched.h)
("sched_getaffinity" sched.h)
("sched_getparam" sched.h)
("sched_getscheduler" sched.h)
("sched_rr_get_interval" sched.h)
("sched_setaffinity" sched.h)
("sched_setparam" sched.h)
("sched_setscheduler" sched.h)
("seed48" stdlib.h)
("seed48_r" stdlib.h)
("seekdir" dirent.h)
("select" sys/select.h unistd.h sys/types.h sys/time.h)
("sem_close" semaphore.h)
("sem_destroy" semaphore.h)
("sem_getvalue" semaphore.h)
("sem_init" semaphore.h)
("sem_open" sys/stat.h fcntl.h semaphore.h)
("sem_post" semaphore.h)
("sem_timedwait" semaphore.h)
("sem_trywait" semaphore.h)
("sem_unlink" semaphore.h)
("sem_wait" semaphore.h)
("semctl" sys/sem.h sys/ipc.h sys/types.h)
("semget" sys/sem.h sys/ipc.h sys/types.h)
("semop" sys/sem.h sys/ipc.h sys/types.h)
("semtimedop" sys/sem.h sys/ipc.h sys/types.h)
("send" sys/socket.h sys/types.h)
("sendfile" sys/sendfile.h)
("sendmsg" sys/socket.h sys/types.h)
("sendto" sys/socket.h sys/types.h)
("set_thread_area" linux/unistd.h asm/ldt.h)
("set_tid_address" linux/unistd.h)
("setaliasent" aliases.h)
("setbuf" stdio.h)
("setbuffer" stdio.h)
("setcontext" ucontext.h)
("setdomainname" unistd.h)
("setegid" unistd.h sys/types.h)
("setenv" stdlib.h)
("seteuid" unistd.h sys/types.h)
("setfsent" fstab.h)
("setfsgid" unistd.h)
("setfsuid" unistd.h)
("setgid" unistd.h sys/types.h)
("sethostent" sys/socket.h netdb.h)
("sethostid" unistd.h)
("sethostname" unistd.h)
("setitimer" sys/time.h)
("setjmp" setjmp.h)
("setkey" stdlib.h unistd.h)
("setkey_r" crypt.h stdlib.h unistd.h)
("setlinebuf" stdio.h)
("setlocale" locale.h)
("setlogmask" syslog.h)
("setmntent" mntent.h stdio.h)
("setnetent" netdb.h)
("setnetgrent" netdb.h)
("setns" sched.h)
("setpgid" unistd.h)
("setpgrp" unistd.h)
("setpriority" sys/resource.h sys/time.h)
("setprotoent" netdb.h)
("setregid" unistd.h sys/types.h)
("setresgid" unistd.h)
("setresuid" unistd.h)
("setreuid" unistd.h sys/types.h)
("setrlimit" sys/resource.h sys/time.h)
("setrpcent" netdb.h)
("setservent" netdb.h)
("setsockopt" sys/socket.h sys/types.h)
("setstate" stdlib.h)
("setstate_r" stdlib.h)
("settimeofday" sys/time.h)
("setttyent" ttyent.h)
("setuid" unistd.h sys/types.h)
("setvbuf" stdio.h)
("sgetspent" shadow.h)
("sgetspent_r" shadow.h)
("shm_open" sys/stat.h sys/mman.h fcntl.h)
("shm_unlink" sys/stat.h sys/mman.h fcntl.h)
("shmat" sys/types.h sys/shm.h)
("shmctl" sys/ipc.h sys/shm.h)
("shmdt" sys/types.h sys/shm.h)
("shmget" sys/ipc.h sys/shm.h)
("shutdown" sys/socket.h)
("sig_atomic_t" signal.h)
("sigaction" signal.h)
("sigaddset" signal.h)
("sigaltstack" signal.h)
("sigblock" signal.h)
("sigdelset" signal.h)
("sigemptyset" signal.h)
("sigfillset" signal.h)
("sighold" signal.h)
("sigignore" signal.h)
("siginterrupt" signal.h)
("sigismember" signal.h)
("siglongjmp" setjmp.h)
("sigmask" signal.h)
("signal" signal.h)
("signalfd" sys/signalfd.h)
("signbit" math.h)
("significand" math.h)
("significandf" math.h)
("significandl" math.h)
("sigpause" signal.h)
("sigpending" signal.h)
("sigprocmask" signal.h)
("sigqueue" signal.h)
("sigrelse" signal.h)
("sigset" signal.h)
("sigsetjmp" setjmp.h)
("sigsetmask" signal.h)
("sigsuspend" signal.h)
("sigtimedwait" signal.h)
("sigvec" signal.h)
("sigwaitinfo" signal.h)
("sin" math.h)
("sincos" math.h)
("sincosf" math.h)
("sincosl" math.h)
("sinf" math.h)
("sinh" math.h)
("sinhf" math.h)
("sinhl" math.h)
("sinl" math.h)
("sleep" unistd.h)
("snprintf" stdio.h)
("sockatmark" sys/socket.h)
("socket" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
("socketpair" sys/socket.h sys/types.h)
("splice" fcntl.h)
("sprintf" stdio.h)
("spu_create" sys/types.h sys/spu.h)
("spu_run" sys/spu.h)
("sqrt" math.h)
("sqrtf" math.h)
("sqrtl" math.h)
("srand" stdlib.h)
("srand48" stdlib.h)
("srand48_r" stdlib.h)
("srandom" stdlib.h)
("srandom_r" stdlib.h)
("sscanf" stdio.h)
("ssignal" signal.h)
("stat" sys/stat.h unistd.h sys/types.h)
("statfs" sys/vfs.h)
("statvfs" sys/statvfs.h)
("stderr" stdio.h)
("stdin" stdio.h)
("stdout" stdio.h)
("stime" time.h)
("stpcpy" string.h)
("stpncpy" string.h)
("strcasecmp" strings.h)
("strcasestr" string.h)
("strcat" string.h)
("strchr" string.h)
("strchrnul" string.h)
("strcmp" string.h)
("strcoll" string.h)
("strcpy" string.h)
("strcspn" string.h)
("strdup" string.h)
("strdupa" string.h)
("strerror" string.h)
("strerror_r" string.h)
("strfmon" monetary.h)
("strfry" string.h)
("strftime" time.h)
("strlen" string.h)
("strncasecmp" strings.h)
("strncat" string)
("strncmp" string.h)
("strncpy" string.h)
("strndup" string.h)
("strndupa" string.h)
("strnlen" string.h)
("strpbrk" string.h)
("strptime" time.h)
("strrchr" string.h)
("strsep" strings.h string.h)
("strsignal" string.h)
("strspn" string.h)
("strstr" string.h)
("strtod" stdlib.h)
("strtof" stdlib.h)
("strtoimax" inttypes.h)
("strtok" string.h)
("strtok_r" string.h)
("strtol" stdlib.h)
("strtold" stdlib.h)
("strtoll" stdlib.h)
("strtoul" stdlib.h)
("strtoull" stdlib.h)
("strtoumax" inttypes.h)
("strverscmp" string.h)
("strxfrm" string.h)
("swab" unistd.h)
("swapcontext" ucontext.h)
("swapoff" sys/swap.h unistd.h asm/page.h)
("swapon" sys/swap.h unistd.h asm/page.h)
("swprintf" wchar.h)
("symlink" unistd.h)
("symlinkat" fcntl.h stdio.h)
("sync_file_range" fcntl.h)
("syncfs" unistd.h)
("syscall" unistd.h sys/syscall.h)
("sysconf" unistd.h)
("sysinfo" sys/sysinfo.h)
("syslog" syslog.h)
("system" stdlib.h)
("sysv_signal" signal.h)
("tan" math.h)
("tanf" math.h)
("tanh" math.h)
("tanhf" math.h)
("tanhl" math.h)
("tanl" math.h)
("tcdrain" unistd.h termios.h)
("tcflow" unistd.h termios.h)
("tcflush" unistd.h termios.h)
("tcgetattr" unistd.h termios.h)
("tcgetpgrp" unistd.h)
("tcgetsid" termios.h)
("tcsendbreak" unistd.h termios.h)
("tcsetattr" unistd.h termios.h)
("tcsetpgrp" unistd.h)
("tdelete" search.h)
("tdestroy" search.h)
("tee" fcntl.h)
("telldir" dirent.h)
("tempnam" stdio.h)
("tfind" search.h)
("tgamma" math.h)
("tgammaf" math.h)
("tgammal" math.h)
("thrd_busy" threads.h)
("thrd_create" threads.h)
("thrd_current" threads.h)
("thrd_detach" threads.h)
("thrd_equal" threads.h)
("thrd_error" threads.h)
("thrd_exit" threads.h)
("thrd_nomem" threads.h)
("thrd_start_t" threads.h)
("thrd_success" threads.h)
("thrd_t" threads.h)
("thrd_timeout" threads.h)
("thrd_yield" threads.h)
("thread_local" threads.h)
("time" time.h)
("time_t" time.h)
("timegm" time.h)
("timelocal" time.h)
("timer_create" time.h signal.h)
("timer_delete" time.h)
("timer_getoverrun" time.h)
("timer_gettime" time.h)
("timer_settime" time.h)
("timeradd" sys/time.h)
("timerclear" sys/time.h)
("timercmp" sys/time.h)
("timerfd_create" sys/timerfd.h)
("timerfd_gettime" sys/timerfd.h)
("timerfd_settime" sys/timerfd.h)
("timerisset" sys/time.h)
("timersub" sys/time.h)
("times" sys/times.h)
("tmpfile" stdio.h)
("tmpnam" stdio.h)
("toascii" ctype.h)
("tolower" ctype.h)
("toupper" ctype.h)
("towctrans" wctype.h)
("towlower" wctype.h)
("towupper" wctype.h)
("trunc" math.h)
("truncate" unistd.h sys/types.h)
("truncf" math.h)
("truncl" math.h)
("tsearch" search.h)
("tss_create" threads.h)
("tss_delete" threads.h)
("tss_dtor_t" threads.h)
("tss_get" threads.h)
("tss_t" threads.h)
("ttyname" unistd.h)
("ttyname_r" unistd.h)
("ttyslot" stdlib.h unistd.h)
("twalk" search.h)
("ualarm" unistd.h)
("uint16_t" stdint.h)
("uint32_t" stdint.h)
("uint64_t" stdint.h)
("uint8_t" stdint.h)
("uint_fast16_t" stdint.h)
("uint_fast32_t" stdint.h)
("uint_fast64_t" stdint.h)
("uint_fast8_t" stdint.h)
("uint_least16_t" stdint.h)
("uint_least32_t" stdint.h)
("uint_least64_t" stdint.h)
("uint_least8_t" stdint.h)
("uintmax_t" stdint.h)
("uintptr_t" stdint.h)
("ulimit" ulimit.h)
("umask" sys/stat.h sys/types.h)
("umount" sys/mount.h)
("umount2" sys/mount.h)
("uname" sys/utsname.h)
("ungetc" stdio.h)
("ungetwc" wchar.h)
("unlink" unistd.h)
("unlinkat" fcntl.h)
("unlockpt" stdlib.h)
("unsetenv" stdlib.h)
("unshare" sched.h)
("updwtmp" utmp.h)
("uselib" unistd.h)
("usleep" unistd.h)
("ustat" unistd.h sys/types.h ustat.h)
("utime" sys/types.h utime.h)
("utimensat" sys/stat.h)
("utimes" sys/types.h sys/time.h utime.h)
("utmpname" utmp.h)
("va_copy" stdarg.h)
("va_end" stdarg.h)
("va_start" stdarg.h)
("valloc" stdlib.h malloc.h)
("vasprintf" stdio.h)
("vdprintf" stdio.h)
("verr" err.h stdarg.h)
("verrx" err.h stdarg.h)
("versionsort" dirent.h)
("vfprintf" stdio.h)
("vfscanf" stdio.h)
("vfwprintf" wchar.h)
("vfwscanf" wchar.h)
("vm86" sys/vm86.h)
("vm86old" sys/vm86.h)
("vmsplice" fcntl.h sys/uio.h)
("vprintf" stdio.h)
("vscanf" stdio.h)
("vsnprintf" stdio.h)
("vsprintf" stdio.h)
("vsscanf" stdio.h)
("vswprintf" wchar.h)
("vswscanf" wchar.h)
("vsyslog" syslog.h stdarg.h)
("vwarn" err.h stdarg.h)
("vwarnx" err.h stdarg.h)
("vwprintf" wchar.h)
("vwscanf" wchar.h)
("wait" sys/wait.h sys/types.h)
("wait3" sys/wait.h sys/resource.h sys/types.h sys/time.h)
("wait4" sys/wait.h sys/resource.h sys/types.h sys/time.h)
("waitid" sys/wait.h sys/types.h)
("waitpid" sys/wait.h sys/types.h)
("warn" err.h)
("warnx" err.h)
("wcpcpy" wchar.h)
("wcpncpy" wchar.h)
("wcrtomb" wchar.h)
("wcscasecmp" wchar.h)
("wcscat" wchar.h)
("wcschr" wchar.h)
("wcscmp" wchar.h)
("wcscoll" wchar.h)
("wcscpy" wchar.h)
("wcscspn" wchar.h)
("wcsdup" wchar.h)
("wcslen" wchar.h)
("wcsncasecmp" wchar.h)
("wcsncat" wchar.h)
("wcsncmp" wchar.h)
("wcsncpy" wchar.h)
("wcsnlen" wchar.h)
("wcsnrtombs" wchar.h)
("wcspbrk" wchar.h)
("wcsrchr" wchar.h)
("wcsrtombs" wchar.h)
("wcsspn" wchar.h)
("wcsstr" wchar.h)
("wcstod" wchar.h)
("wcstof" wchar.h)
("wcstoimax" stddef.h inttypes.h)
("wcstok" wchar.h)
("wcstol" cwchar)
("wcstold" wchar.h)
("wcstoll" cwchar)
("wcstombs" stdlib.h)
("wcstoul" wchar.h)
("wcstoull" wchar.h)
("wcstoumax" stddef.h inttypes.h)
("wcswidth" wchar.h)
("wctob" wchar.h)
("wctomb" stdlib.h)
("wctrans" wctype.h)
("wctype" wctype.h)
("wcwidth" wchar.h)
("wmemchr" wchar.h)
("wmemcmp" wchar.h)
("wmemcpy" wchar.h)
("wmemmove" wchar.h)
("wmempcpy" string.h wchar.h)
("wmemset" wchar.h)
("wordexp" wordexp.h)
("wordfree" wordexp.h)
("wprintf" wchar.h)
("write" unistd.h)
("writev" sys/uio.h)
("xdecrypt" rpc/des_crypt.h)
("xencrypt" rpc/des_crypt.h)
("y0" math.h)
("y0f" math.h)
("y0l" math.h)
("y1" math.h)
("y1f" math.h)
("y1l" math.h)
("yn" math.h)
("ynf" math.h)
("ynl" math.h)
))
