(setq includeme-index-c '(("getopt_long" getopt.h unistd.h)
(("atomic_fetch_xor" stdatomic.h)
(("SCNXLEAST32" stdint.h)
(("LDBL_MAX_10_EXP" stdint.h)
(("FE_DFL_ENV" fenv.h)
(("CPU_EQUAL_S" sched.h)
(("CMSG_ALIGN" sys/socket.h)
(("ATOMIC_POINTER_LOCK_FREE" stdatomic.h)
(("ATOMIC_CHAR_LOCK_FREE" stdatomic.h)
(("ATOMIC_CHAR16_LOCK_FREE" stdatomic.h)
(("ATOMIC_BOOL_LOCK_FREE" stdatomic.h)
nil . nil) . (("ATOMIC_CHAR32_LOCK_FREE" stdatomic.h)
nil . nil)) . (("ATOMIC_LLONG_LOCK_FREE" stdatomic.h)
(("ATOMIC_INT_LOCK_FREE" stdatomic.h)
nil . nil) . (("ATOMIC_LONG_LOCK_FREE" stdatomic.h)
nil . nil))) . (("BUFSIZ" stdio.h)
(("ATOMIC_VAR_INIT" stdatomic.h)
(("ATOMIC_SHORT_LOCK_FREE" stdatomic.h)
nil . nil) . (("ATOMIC_WCHAR_T_LOCK_FREE" stdatomic.h)
nil . nil)) . (("CHAR_MAX" stdint.h)
(("CHAR_BIT" stdint.h)
nil . nil) . (("CHAR_MIN" stdint.h)
nil . nil)))) . (("CPU_AND" sched.h)
(("CMSG_NXTHDR" sys/socket.h)
(("CMSG_FIRSTHDR" sys/socket.h)
(("CMSG_DATA" sys/socket.h)
nil . nil) . (("CMSG_LEN" sys/socket.h)
nil . nil)) . (("CPU_ALLOC" sched.h)
(("CMSG_SPACE" sys/socket.h)
nil . nil) . (("CPU_ALLOC_SIZE" sched.h)
nil . nil))) . (("CPU_COUNT" sched.h)
(("CPU_CLR" sched.h)
(("CPU_AND_S" sched.h)
nil . nil) . (("CPU_CLR_S" sched.h)
nil . nil)) . (("CPU_EQUAL" sched.h)
(("CPU_COUNT_S" sched.h)
nil . nil) . nil)))) . (("DBL_MAX_10_EXP" stdint.h)
(("CPU_XOR" sched.h)
(("CPU_OR" sched.h)
(("CPU_ISSET" sched.h)
(("CPU_FREE" sched.h)
nil . nil) . (("CPU_ISSET_S" sched.h)
nil . nil)) . (("CPU_SET" sched.h)
(("CPU_OR_S" sched.h)
nil . nil) . (("CPU_SET_S" sched.h)
nil . nil))) . (("DBL_DIG" stdint.h)
(("CPU_ZERO" sched.h)
(("CPU_XOR_S" sched.h)
nil . nil) . (("CPU_ZERO_S" sched.h)
nil . nil)) . (("DBL_MANT_DIG" stdint.h)
(("DBL_EPSILON" stdint.h)
nil . nil) . (("DBL_MAX" stdint.h)
nil . nil)))) . (("EXIT_FAILURE" stdlib.h)
(("DBL_MIN_EXP" stdint.h)
(("DBL_MIN" stdint.h)
(("DBL_MAX_EXP" stdint.h)
nil . nil) . (("DBL_MIN_10_EXP" stdint.h)
nil . nil)) . (("DES_FAILED" rpc/des_crypt.h)
(("DECIMAL_DIG" stdint.h)
nil . nil) . (("EOF" stdio.h)
nil . nil))) . (("FD_SET" sys/select.h unistd.h sys/types.h sys/time.h)
(("FD_CLR" sys/select.h unistd.h sys/types.h sys/time.h)
(("EXIT_SUCCESS" stdlib.h)
nil . nil) . (("FD_ISSET" sys/select.h unistd.h sys/types.h sys/time.h)
nil . nil)) . (("FE_ALL_EXCEPT" fenv.h)
(("FD_ZERO" sys/select.h unistd.h sys/types.h sys/time.h)
nil . nil) . nil))))) . (("INT32_MIN" stdint.h)
(("FLT_MAX" stdint.h)
(("FE_UNHERFLOW" fenv.h)
(("FE_INVALID" fenv.h)
(("FE_DOWNWARD" fenv.h)
(("FE_DIVBYZERO" fenv.h)
nil . nil) . (("FE_INEXACT" fenv.h)
nil . nil)) . (("FE_TONEAREST" fenv.h)
(("FE_OVERFLOW" fenv.h)
nil . nil) . (("FE_TOWARDZERO" fenv.h)
nil . nil))) . (("FLT_DIG" stdint.h)
(("FILE" stdio.h)
(("FE_UPWARD" fenv.h)
nil . nil) . (("FILENAME_MAX" stdio.h)
nil . nil)) . (("FLT_EVAL_METHOD" float.h)
(("FLT_EPSILON" stdint.h)
nil . nil) . (("FLT_MANT_DIG" stdint.h)
nil . nil)))) . (("FOPEN_MAX" stdio.h)
(("FLT_MIN_10_EXP" stdint.h)
(("FLT_MAX_EXP" stdint.h)
(("FLT_MAX_10_EXP" stdint.h)
nil . nil) . (("FLT_MIN" stdint.h)
nil . nil)) . (("FLT_RADIX" stdint.h)
(("FLT_MIN_EXP" stdint.h)
nil . nil) . (("FLT_ROUNDS" float.h)
nil . nil))) . (("INT16_MAX" stdint.h)
(("HUGE_VALF" math.h)
(("HUGE_VAL" math.h)
nil . nil) . (("HUGE_VALL" math.h)
nil . nil)) . (("INT32_MAX" stdint.h)
(("INT16_MIN" stdint.h)
nil . nil) . nil)))) . (("INT_FAST8_MIN" stdint.h)
(("INTPTR_MIN" stdint.h)
(("INT8_MIN" stdint.h)
(("INT64_MIN" stdint.h)
(("INT64_MAX" stdint.h)
nil . nil) . (("INT8_MAX" stdint.h)
nil . nil)) . (("INTMAX_MIN" stdint.h)
(("INTMAX_MAX" stdint.h)
nil . nil) . (("INTPTR_MAX" stdint.h)
nil . nil))) . (("INT_FAST32_MIN" stdint.h)
(("INT_FAST16_MIN" stdint.h)
(("INT_FAST16_MAX" stdint.h)
nil . nil) . (("INT_FAST32_MAX" stdint.h)
nil . nil)) . (("INT_FAST64_MIN" stdint.h)
(("INT_FAST64_MAX" stdint.h)
nil . nil) . (("INT_FAST8_MAX" stdint.h)
nil . nil)))) . (("INT_LEAST8_MIN" stdint.h)
(("INT_LEAST32_MIN" stdint.h)
(("INT_LEAST16_MIN" stdint.h)
(("INT_LEAST16_MAX" stdint.h)
nil . nil) . (("INT_LEAST32_MAX" stdint.h)
nil . nil)) . (("INT_LEAST64_MIN" stdint.h)
(("INT_LEAST64_MAX" stdint.h)
nil . nil) . (("INT_LEAST8_MAX" stdint.h)
nil . nil))) . (("LDBL_EPSILON" stdint.h)
(("INT_MIN" stdint.h)
(("INT_MAX" stdint.h)
nil . nil) . (("LDBL_DIG" stdint.h)
nil . nil)) . (("LDBL_MAX" stdint.h)
(("LDBL_MANT_DIG" stdint.h)
nil . nil) . nil)))))) . (("PRIo32" stdint.h)
(("PRIXMAX" stdint.h)
(("NLMSG_PAYLOAD" asm/types.h linux/netlink.h)
(("LONG_MIN" stdint.h)
(("LDBL_MIN_EXP" stdint.h)
(("LDBL_MIN" stdint.h)
(("LDBL_MAX_EXP" stdint.h)
nil . nil) . (("LDBL_MIN_10_EXP" stdint.h)
nil . nil)) . (("LLONG_MIN" stdint.h)
(("LLONG_MAX" stdint.h)
nil . nil) . (("LONG_MAX" stdint.h)
nil . nil))) . (("NLMSG_DATA" asm/types.h linux/netlink.h)
(("MB_LEN_MAX" stdint.h)
(("L_tmpnam" stdio.h)
nil . nil) . (("NLMSG_ALIGN" asm/types.h linux/netlink.h)
nil . nil)) . (("NLMSG_NEXT" asm/types.h linux/netlink.h)
(("NLMSG_LENGTH" asm/types.h linux/netlink.h)
nil . nil) . (("NLMSG_OK" asm/types.h linux/netlink.h)
nil . nil)))) . (("PRIXFAST32" stdint.h)
(("PRIX32" stdint.h)
(("ONCE_FLAG_INIT" threads.h)
(("NLMSG_SPACE" asm/types.h linux/netlink.h)
nil . nil) . (("PRIX16" stdint.h)
nil . nil)) . (("PRIX8" stdint.h)
(("PRIX64" stdint.h)
nil . nil) . (("PRIXFAST16" stdint.h)
nil . nil))) . (("PRIXLEAST32" stdint.h)
(("PRIXFAST8" stdint.h)
(("PRIXFAST64" stdint.h)
nil . nil) . (("PRIXLEAST16" stdint.h)
nil . nil)) . (("PRIXLEAST8" stdint.h)
(("PRIXLEAST64" stdint.h)
nil . nil) . nil)))) . (("PRIi16" stdint.h)
(("PRIdFAST64" stdint.h)
(("PRId64" stdint.h)
(("PRId16" stdint.h)
(("PRIXPTR " stdint.h)
nil . nil) . (("PRId32" stdint.h)
nil . nil)) . (("PRIdFAST16" stdint.h)
(("PRId8" stdint.h)
nil . nil) . (("PRIdFAST32" stdint.h)
nil . nil))) . (("PRIdLEAST64" stdint.h)
(("PRIdLEAST16" stdint.h)
(("PRIdFAST8" stdint.h)
nil . nil) . (("PRIdLEAST32" stdint.h)
nil . nil)) . (("PRIdMAX" stdint.h)
(("PRIdLEAST8" stdint.h)
nil . nil) . (("PRIdPTR " stdint.h)
nil . nil)))) . (("PRIiLEAST16" stdint.h)
(("PRIiFAST16" stdint.h)
(("PRIi64" stdint.h)
(("PRIi32" stdint.h)
nil . nil) . (("PRIi8" stdint.h)
nil . nil)) . (("PRIiFAST64" stdint.h)
(("PRIiFAST32" stdint.h)
nil . nil) . (("PRIiFAST8" stdint.h)
nil . nil))) . (("PRIiMAX" stdint.h)
(("PRIiLEAST64" stdint.h)
(("PRIiLEAST32" stdint.h)
nil . nil) . (("PRIiLEAST8" stdint.h)
nil . nil)) . (("PRIo16" stdint.h)
(("PRIiPTR " stdint.h)
nil . nil) . nil))))) . (("PRIxFAST16" stdint.h)
(("PRIu8" stdint.h)
(("PRIoLEAST32" stdint.h)
(("PRIoFAST32" stdint.h)
(("PRIo8" stdint.h)
(("PRIo64" stdint.h)
nil . nil) . (("PRIoFAST16" stdint.h)
nil . nil)) . (("PRIoFAST8" stdint.h)
(("PRIoFAST64" stdint.h)
nil . nil) . (("PRIoLEAST16" stdint.h)
nil . nil))) . (("PRIoPTR " stdint.h)
(("PRIoLEAST8" stdint.h)
(("PRIoLEAST64" stdint.h)
nil . nil) . (("PRIoMAX" stdint.h)
nil . nil)) . (("PRIu32" stdint.h)
(("PRIu16" stdint.h)
nil . nil) . (("PRIu64" stdint.h)
nil . nil)))) . (("PRIuLEAST8" stdint.h)
(("PRIuFAST8" stdint.h)
(("PRIuFAST32" stdint.h)
(("PRIuFAST16" stdint.h)
nil . nil) . (("PRIuFAST64" stdint.h)
nil . nil)) . (("PRIuLEAST32" stdint.h)
(("PRIuLEAST16" stdint.h)
nil . nil) . (("PRIuLEAST64" stdint.h)
nil . nil))) . (("PRIx32" stdint.h)
(("PRIuPTR " stdint.h)
(("PRIuMAX" stdint.h)
nil . nil) . (("PRIx16" stdint.h)
nil . nil)) . (("PRIx8" stdint.h)
(("PRIx64" stdint.h)
nil . nil) . nil)))) . (("RTA_NEXT" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
(("PRIxMAX" stdint.h)
(("PRIxLEAST16" stdint.h)
(("PRIxFAST64" stdint.h)
(("PRIxFAST32" stdint.h)
nil . nil) . (("PRIxFAST8" stdint.h)
nil . nil)) . (("PRIxLEAST64" stdint.h)
(("PRIxLEAST32" stdint.h)
nil . nil) . (("PRIxLEAST8" stdint.h)
nil . nil))) . (("RAND_MAX" stdlib.h)
(("PTRDIFF_MAX" stdint.h)
(("PRIxPTR " stdint.h)
nil . nil) . (("PTRDIFF_MIN" stdint.h)
nil . nil)) . (("RTA_LENGTH" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
(("RTA_DATA" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
nil . nil) . nil))) . (("SCNX64" stdint.h)
(("SCHAR_MAX" stdint.h)
(("RTA_PAYLOAD" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
(("RTA_OK" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
nil . nil) . (("RTA_SPACE" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
nil . nil)) . (("SCNX16" stdint.h)
(("SCHAR_MIN" stdint.h)
nil . nil) . (("SCNX32" stdint.h)
nil . nil))) . (("SCNXFAST64" stdint.h)
(("SCNXFAST16" stdint.h)
(("SCNX8" stdint.h)
nil . nil) . (("SCNXFAST32" stdint.h)
nil . nil)) . (("SCNXLEAST16" stdint.h)
(("SCNXFAST8" stdint.h)
nil . nil) . nil))))))) . (("__freadable" stdio_ext.h stdio.h)
(("SCNx32" stdint.h)
(("SCNiMAX" stdint.h)
(("SCNdLEAST8" stdint.h)
(("SCNd8" stdint.h)
(("SCNXPTR" stdint.h)
(("SCNXLEAST8" stdint.h)
(("SCNXLEAST64" stdint.h)
nil . nil) . (("SCNXMAX" stdint.h)
nil . nil)) . (("SCNd32" stdint.h)
(("SCNd16" stdint.h)
nil . nil) . (("SCNd64" stdint.h)
nil . nil))) . (("SCNdFAST8" stdint.h)
(("SCNdFAST32" stdint.h)
(("SCNdFAST16" stdint.h)
nil . nil) . (("SCNdFAST64" stdint.h)
nil . nil)) . (("SCNdLEAST32" stdint.h)
(("SCNdLEAST16" stdint.h)
nil . nil) . (("SCNdLEAST64" stdint.h)
nil . nil)))) . (("SCNiFAST32" stdint.h)
(("SCNi32" stdint.h)
(("SCNdPTR " stdint.h)
(("SCNdMAX" stdint.h)
nil . nil) . (("SCNi16" stdint.h)
nil . nil)) . (("SCNi8" stdint.h)
(("SCNi64" stdint.h)
nil . nil) . (("SCNiFAST16" stdint.h)
nil . nil))) . (("SCNiLEAST32" stdint.h)
(("SCNiFAST8" stdint.h)
(("SCNiFAST64" stdint.h)
nil . nil) . (("SCNiLEAST16" stdint.h)
nil . nil)) . (("SCNiLEAST8" stdint.h)
(("SCNiLEAST64" stdint.h)
nil . nil) . nil)))) . (("SCNu16" stdint.h)
(("SCNoFAST64" stdint.h)
(("SCNo64" stdint.h)
(("SCNo16" stdint.h)
(("SCNiPTR " stdint.h)
nil . nil) . (("SCNo32" stdint.h)
nil . nil)) . (("SCNoFAST16" stdint.h)
(("SCNo8" stdint.h)
nil . nil) . (("SCNoFAST32" stdint.h)
nil . nil))) . (("SCNoLEAST64" stdint.h)
(("SCNoLEAST16" stdint.h)
(("SCNoFAST8" stdint.h)
nil . nil) . (("SCNoLEAST32" stdint.h)
nil . nil)) . (("SCNoMAX" stdint.h)
(("SCNoLEAST8" stdint.h)
nil . nil) . (("SCNoPTR " stdint.h)
nil . nil)))) . (("SCNuLEAST16" stdint.h)
(("SCNuFAST16" stdint.h)
(("SCNu64" stdint.h)
(("SCNu32" stdint.h)
nil . nil) . (("SCNu8" stdint.h)
nil . nil)) . (("SCNuFAST64" stdint.h)
(("SCNuFAST32" stdint.h)
nil . nil) . (("SCNuFAST8" stdint.h)
nil . nil))) . (("SCNuMAX" stdint.h)
(("SCNuLEAST64" stdint.h)
(("SCNuLEAST32" stdint.h)
nil . nil) . (("SCNuLEAST8" stdint.h)
nil . nil)) . (("SCNx16" stdint.h)
(("SCNuPTR " stdint.h)
nil . nil) . nil))))) . (("UINT16_MAX" stdint.h)
(("SHRT_MAX" stdint.h)
(("SCNxLEAST32" stdint.h)
(("SCNxFAST32" stdint.h)
(("SCNx8" stdint.h)
(("SCNx64" stdint.h)
nil . nil) . (("SCNxFAST16" stdint.h)
nil . nil)) . (("SCNxFAST8" stdint.h)
(("SCNxFAST64" stdint.h)
nil . nil) . (("SCNxLEAST16" stdint.h)
nil . nil))) . (("SCNxPTR " stdint.h)
(("SCNxLEAST8" stdint.h)
(("SCNxLEAST64" stdint.h)
nil . nil) . (("SCNxMAX" stdint.h)
nil . nil)) . (("SEEK_END" stdio.h)
(("SEEK_CUR" stdio.h)
nil . nil) . (("SEEK_SET" stdio.h)
nil . nil)))) . (("SIG_ATOMIC_MAX" stdint.h)
(("SIGILL" signal.h)
(("SIGABRT" signal.h)
(("SHRT_MIN" stdint.h)
nil . nil) . (("SIGFPE" signal.h)
nil . nil)) . (("SIGSEGV" signal.h)
(("SIGINT" signal.h)
nil . nil) . (("SIGTERM" signal.h)
nil . nil))) . (("TMP_MAX" stdio.h)
(("SIG_ERR" signal.h)
(("SIG_ATOMIC_MIN" stdint.h)
nil . nil) . (("SIZE_MAX" stdint.h)
nil . nil)) . (("UCHAR_MAX" stdint.h)
(("TSS_DTOR_ITERATIONS" threads.h)
nil . nil) . nil)))) . (("ULLONG_MAX" stdint.h)
(("UINT_FAST64_MAX" stdint.h)
(("UINTMAX_MAX" stdint.h)
(("UINT64_MAX" stdint.h)
(("UINT32_MAX" stdint.h)
nil . nil) . (("UINT8_MAX" stdint.h)
nil . nil)) . (("UINT_FAST16_MAX" stdint.h)
(("UINTPTR_MAX" stdint.h)
nil . nil) . (("UINT_FAST32_MAX" stdint.h)
nil . nil))) . (("UINT_LEAST64_MAX" stdint.h)
(("UINT_LEAST16_MAX" stdint.h)
(("UINT_FAST8_MAX" stdint.h)
nil . nil) . (("UINT_LEAST32_MAX" stdint.h)
nil . nil)) . (("UINT_MAX" stdint.h)
(("UINT_LEAST8_MAX" stdint.h)
nil . nil) . nil))) . (("_IOFBF" stdio.h)
(("WCHAR_MIN" stdint.h)
(("USHRT_MAX" stdint.h)
(("ULONG_MAX" stdint.h)
nil . nil) . (("WCHAR_MAX" stdint.h)
nil . nil)) . (("WINT_MIN" stdint.h)
(("WINT_MAX" stdint.h)
nil . nil) . (("_Exit" stdlib.h unistd.h)
nil . nil))) . (("__flbf" stdio_ext.h stdio.h)
(("_IONBF" stdio.h)
(("_IOLBF" stdio.h)
nil . nil) . (("__fbufsize" stdio_ext.h stdio.h)
nil . nil)) . (("__fpurge" stdio_ext.h stdio.h)
(("__fpending" stdio_ext.h stdio.h)
nil . nil) . nil)))))) . (("asn1_create_element" libtasn1.h)
(("aio_return" aio.h)
(("acos" math.h)
(("_llseek" unistd.h sys/types.h)
(("__fwriting" stdio_ext.h stdio.h)
(("__fsetlocking" stdio_ext.h stdio.h)
(("__freading" stdio_ext.h stdio.h)
nil . nil) . (("__fwritable" stdio_ext.h stdio.h)
nil . nil)) . (("_exit" unistd.h)
(("__setfpucw" i386/fpu_control.h)
nil . nil) . (("_flushlbf" stdio_ext.h stdio.h)
nil . nil))) . (("accept" sys/socket.h sys/types.h)
(("a64l" stdlib.h)
(("_sysctl" unistd.h linux/sysctl.h)
nil . nil) . (("abs" stdlib.h)
nil . nil)) . (("access" unistd.h)
(("accept4" sys/socket.h sys/types.h)
nil . nil) . (("acct" unistd.h)
nil . nil)))) . (("addseverity" fmtmsg.h)
(("acoshl" math.h)
(("acosh" math.h)
(("acosf" math.h)
nil . nil) . (("acoshf" math.h)
nil . nil)) . (("add_key" keyutils.h)
(("acosl" math.h)
nil . nil) . (("addmntent" mntent.h stdio.h)
nil . nil))) . (("aio_fsync" aio.h)
(("aio_cancel" aio.h)
(("adjtimex" sys/timex.h)
nil . nil) . (("aio_error" aio.h)
nil . nil)) . (("aio_read" aio.h)
(("aio_init" aio.h)
nil . nil) . nil)))) . (("argz_next" argz.h)
(("argz_add_sep" argz.h)
(("alloca" alloca.h)
(("aio_write" aio.h)
(("aio_suspend" aio.h)
nil . nil) . (("alarm" unistd.h)
nil . nil)) . (("arch_prctl" asm/prctl.h sys/prctl.h)
(("alphasort" dirent.h)
nil . nil) . (("argz_add" argz.h)
nil . nil))) . (("argz_create_sep" argz.h)
(("argz_count" argz.h)
(("argz_append" argz.h)
nil . nil) . (("argz_create" argz.h)
nil . nil)) . (("argz_extract" argz.h)
(("argz_delete" argz.h)
nil . nil) . (("argz_insert" argz.h)
nil . nil)))) . (("asinhf" math.h)
(("asctime_r" time.h)
(("argz_stringify" argz.h)
(("argz_replace" argz.h)
nil . nil) . (("asctime" time.h)
nil . nil)) . (("asinf" math.h)
(("asin" math.h)
nil . nil) . (("asinh" math.h)
nil . nil))) . (("asn1_bit_der" libtasn1.h)
(("asinl" math.h)
(("asinhl" math.h)
nil . nil) . (("asn1_array2tree" libtasn1.h)
nil . nil)) . (("asn1_copy_node" libtasn1.h)
(("asn1_check_version" libtasn1.h)
nil . nil) . nil))))) . (("atan" math.h)
(("asn1_length_der" libtasn1.h)
(("asn1_expand_octet_string" libtasn1.h)
(("asn1_der_decoding" libtasn1.h)
(("asn1_delete_structure" libtasn1.h)
(("asn1_delete_element" libtasn1.h)
nil . nil) . (("asn1_der_coding" libtasn1.h)
nil . nil)) . (("asn1_der_decoding_startEnd" libtasn1.h)
(("asn1_der_decoding_element" libtasn1.h)
nil . nil) . (("asn1_expand_any_defined_by" libtasn1.h)
nil . nil))) . (("asn1_get_length_ber" libtasn1.h)
(("asn1_find_structure_from_oid" libtasn1.h)
(("asn1_find_node" libtasn1.h)
nil . nil) . (("asn1_get_bit_der" libtasn1.h)
nil . nil)) . (("asn1_get_octet_der" libtasn1.h)
(("asn1_get_length_der" libtasn1.h)
nil . nil) . (("asn1_get_tag_der" libtasn1.h)
nil . nil)))) . (("asn1_read_value" libtasn1.h)
(("asn1_parser2tree" libtasn1.h)
(("asn1_octet_der" libtasn1.h)
(("asn1_number_of_elements" libtasn1.h)
nil . nil) . (("asn1_parser2array" libtasn1.h)
nil . nil)) . (("asn1_print_structure" libtasn1.h)
(("asn1_perror" libtasn1.h)
nil . nil) . (("asn1_read_tag" libtasn1.h)
nil . nil))) . (("assert" assert.h)
(("asn1_write_value" libtasn1.h)
(("asn1_strerror" libtasn1.h)
nil . nil) . (("asprintf" stdio.h)
nil . nil)) . (("at_quick_exit" stdlib.h)
(("assert_perror" assert.h)
nil . nil) . nil)))) . (("atomic_char" stdatomic.h)
(("atanl" math.h)
(("atanf" math.h)
(("atan2f" math.h)
(("atan2" math.h)
nil . nil) . (("atan2l" math.h)
nil . nil)) . (("atanhf" math.h)
(("atanh" math.h)
nil . nil) . (("atanhl" math.h)
nil . nil))) . (("atol" stdlib.h)
(("atof" stdlib.h)
(("atexit" stdlib.h)
nil . nil) . (("atoi" stdlib.h)
nil . nil)) . (("atomic_bool" stdatomic.h)
(("atoll" stdlib.h)
nil . nil) . nil))) . (("atomic_exchange_explicit" stdatomic.h)
(("atomic_compare_exchange_strong_explicit" stdatomic.h)
(("atomic_char32_t" stdatomic.h)
(("atomic_char16_t" stdatomic.h)
nil . nil) . (("atomic_compare_exchange_strong" stdatomic.h)
nil . nil)) . (("atomic_compare_exchange_weak_explicit" stdatomic.h)
(("atomic_compare_exchange_weak" stdatomic.h)
nil . nil) . (("atomic_exchange" stdatomic.h)
nil . nil))) . (("atomic_fetch_and_explicit" stdatomic.h)
(("atomic_fetch_add_explicit" stdatomic.h)
(("atomic_fetch_add" stdatomic.h)
nil . nil) . (("atomic_fetch_and" stdatomic.h)
nil . nil)) . (("atomic_fetch_or_explicit" stdatomic.h)
(("atomic_fetch_or" stdatomic.h)
nil . nil) . nil)))))))) . (("erand48" stdlib.h)
(("chdir" unistd.h)
(("cacos" complex.h)
(("atomic_uint_least16_t" stdatomic.h)
(("atomic_llong" stdatomic.h)
(("atomic_int_fast8_t" stdatomic.h)
(("atomic_int" stdatomic.h)
(("atomic_flag" stdatomic.h)
(("atomic_fetch_xor_explicit" stdatomic.h)
nil . nil) . (("atomic_init" stdatomic.h)
nil . nil)) . (("atomic_int_fast32_t" stdatomic.h)
(("atomic_int_fast16_t" stdatomic.h)
nil . nil) . (("atomic_int_fast64_t" stdatomic.h)
nil . nil))) . (("atomic_int_least8_t" stdatomic.h)
(("atomic_int_least32_t" stdatomic.h)
(("atomic_int_least16_t" stdatomic.h)
nil . nil) . (("atomic_int_least64_t" stdatomic.h)
nil . nil)) . (("atomic_intprt_t" stdatomic.h)
(("atomic_intmax_t" stdatomic.h)
nil . nil) . (("atomic_is_lock_free" stdatomic.h)
nil . nil)))) . (("atomic_store_explicit" stdatomic.h)
(("atomic_short" stdatomic.h)
(("atomic_ptrdiff_t" stdatomic.h)
(("atomic_long" stdatomic.h)
nil . nil) . (("atomic_schar" stdatomic.h)
nil . nil)) . (("atomic_size_t" stdatomic.h)
(("atomic_signal_fence" stdatomic.h)
nil . nil) . (("atomic_store" stdatomic.h)
nil . nil))) . (("atomic_uint_fast32_t" stdatomic.h)
(("atomic_uint" stdatomic.h)
(("atomic_uchar" stdatomic.h)
nil . nil) . (("atomic_uint_fast16_t" stdatomic.h)
nil . nil)) . (("atomic_uint_fast8_t" stdatomic.h)
(("atomic_uint_fast64_t" stdatomic.h)
nil . nil) . nil)))) . (("be32toh" endian.h)
(("atomic_ushort" stdatomic.h)
(("atomic_uintmax_t" stdatomic.h)
(("atomic_uint_least64_t" stdatomic.h)
(("atomic_uint_least32_t" stdatomic.h)
nil . nil) . (("atomic_uint_least8_t" stdatomic.h)
nil . nil)) . (("atomic_ullong" stdatomic.h)
(("atomic_uintprt_t" stdatomic.h)
nil . nil) . (("atomic_ulong" stdatomic.h)
nil . nil))) . (("bcmp" strings.h)
(("atoq" stdlib.h)
(("atomic_wchar_t" stdatomic.h)
nil . nil) . (("basename" libgen.h)
nil . nil)) . (("bdflush" sys/kdaemon.h)
(("bcopy" strings.h)
nil . nil) . (("be16toh" endian.h)
nil . nil)))) . (("bzero" strings.h)
(("brk" unistd.h)
(("bind" sys/socket.h sys/types.h)
(("be64toh" endian.h)
nil . nil) . (("bindresvport" sys/types.h netinet/in.h)
nil . nil)) . (("bsearch" stdlib.h)
(("bsd_signal" signal.h)
nil . nil) . (("btowc" wchar.h)
nil . nil))) . (("cabsf" complex.h)
(("c32rtomb" uchar.h)
(("c16rtomb" uchar.h)
nil . nil) . (("cabs" complex.h)
nil . nil)) . (("cacheflush" asm/cachectl.h)
(("cabsl" complex.h)
nil . nil) . nil))))) . (("cbrtf" math.h)
(("casinh" complex.h)
(("canonicalize_file_name" stdlib.h)
(("cacoshl" complex.h)
(("cacosh" complex.h)
(("cacosf" complex.h)
nil . nil) . (("cacoshf" complex.h)
nil . nil)) . (("call_once" threads.h)
(("cacosl" complex.h)
nil . nil) . (("calloc" stdlib.h)
nil . nil))) . (("cargf" complex.h)
(("capset" sys/capability.h)
(("capget" sys/capability.h)
nil . nil) . (("carg" complex.h)
nil . nil)) . (("casin" complex.h)
(("cargl" complex.h)
nil . nil) . (("casinf" complex.h)
nil . nil)))) . (("catanhl" complex.h)
(("catan" complex.h)
(("casinhl" complex.h)
(("casinhf" complex.h)
nil . nil) . (("casinl" complex.h)
nil . nil)) . (("catanh" complex.h)
(("catanf" complex.h)
nil . nil) . (("catanhf" complex.h)
nil . nil))) . (("catopen" nl_types.h)
(("catclose" nl_types.h)
(("catanl" complex.h)
nil . nil) . (("catgets" nl_types.h)
nil . nil)) . (("cbrt" math.h)
(("cbc_crypt" rpc/des_crypt.h)
nil . nil) . nil)))) . (("cerff" complex.h)
(("ceil" math.h)
(("ccosh" complex.h)
(("ccos" complex.h)
(("cbrtl" math.h)
nil . nil) . (("ccosf" complex.h)
nil . nil)) . (("ccoshl" complex.h)
(("ccoshf" complex.h)
nil . nil) . (("ccosl" complex.h)
nil . nil))) . (("cerfc" complex.h)
(("ceill" math.h)
(("ceilf" math.h)
nil . nil) . (("cerf" complex.h)
nil . nil)) . (("cerfcl" complex.h)
(("cerfcf" complex.h)
nil . nil) . nil))) . (("cfgetispeed" unistd.h termios.h)
(("cexp2f" complex.h)
(("cexp" complex.h)
(("cerfl" complex.h)
nil . nil) . (("cexp2" complex.h)
nil . nil)) . (("cexpf" complex.h)
(("cexp2l" complex.h)
nil . nil) . (("cexpl" complex.h)
nil . nil))) . (("cfsetispeed" unistd.h termios.h)
(("cfmakeraw" unistd.h termios.h)
(("cfgetospeed" unistd.h termios.h)
nil . nil) . (("cfree" stdlib.h)
nil . nil)) . (("cfsetspeed" unistd.h termios.h)
(("cfsetospeed" unistd.h termios.h)
nil . nil) . nil)))))) . (("csinf" complex.h)
(("cnd_t" threads.h)
(("clog" complex.h)
(("clearerr" stdio.h)
(("cimag" complex.h)
(("chown" unistd.h)
(("chmod" sys/stat.h)
nil . nil) . (("chroot" unistd.h)
nil . nil)) . (("cimagl" complex.h)
(("cimagf" complex.h)
nil . nil) . (("clearenv" stdlib.h)
nil . nil))) . (("clock_gettime" time.h)
(("clock_getcpuclockid" time.h)
(("clearerr_unlocked" stdio.h)
nil . nil) . (("clock_getres" time.h)
nil . nil)) . (("clock_settime" time.h)
(("clock_nanosleep" time.h)
nil . nil) . (("clock_t" time.h)
nil . nil)))) . (("clogl" complex.h)
(("clog2" complex.h)
(("clog10f" complex.h)
(("clog10" complex.h)
nil . nil) . (("clog10l" complex.h)
nil . nil)) . (("clog2l" complex.h)
(("clog2f" complex.h)
nil . nil) . (("clogf" complex.h)
nil . nil))) . (("closelog" syslog.h)
(("close" unistd.h)
(("clone" sched.h)
nil . nil) . (("closedir" sys/types.h dirent.h)
nil . nil)) . (("cnd_init" threads.h)
(("cnd_broadcast" threads.h)
nil . nil) . nil)))) . (("cosl" math.h)
(("copysign" math.h)
(("conj" complex.h)
(("cnd_wait" threads.h)
(("cnd_timedwait" threads.h)
nil . nil) . (("confstr" unistd.h)
nil . nil)) . (("conjl" complex.h)
(("conjf" complex.h)
nil . nil) . (("connect" sys/socket.h sys/types.h)
nil . nil))) . (("cosf" math.h)
(("copysignl" math.h)
(("copysignf" math.h)
nil . nil) . (("cos" math.h)
nil . nil)) . (("coshf" math.h)
(("cosh" math.h)
nil . nil) . (("coshl" math.h)
nil . nil)))) . (("crealf" complex.h)
(("cproj" complex.h)
(("cpowf" complex.h)
(("cpow" complex.h)
nil . nil) . (("cpowl" complex.h)
nil . nil)) . (("cprojl" complex.h)
(("cprojf" complex.h)
nil . nil) . (("creal" complex.h)
nil . nil))) . (("crypt" unistd.h)
(("creat" sys/stat.h sys/types.h fcntl.h)
(("creall" complex.h)
nil . nil) . (("create_module" linux/module.h)
nil . nil)) . (("csin" complex.h)
(("crypt_r" crypt.h unistd.h)
nil . nil) . nil))))) . (("dn_expand" arpa/nameser.h netinet/in.h resolv.h)
(("ctime_r" time.h)
(("ctan" complex.h)
(("csinl" complex.h)
(("csinhf" complex.h)
(("csinh" complex.h)
nil . nil) . (("csinhl" complex.h)
nil . nil)) . (("csqrtf" complex.h)
(("csqrt" complex.h)
nil . nil) . (("csqrtl" complex.h)
nil . nil))) . (("ctanhl" complex.h)
(("ctanh" complex.h)
(("ctanf" complex.h)
nil . nil) . (("ctanhf" complex.h)
nil . nil)) . (("ctermid" stdio.h)
(("ctanl" complex.h)
nil . nil) . (("ctime" time.h)
nil . nil)))) . (("dirname" libgen.h)
(("delete_module" linux/module.h)
(("daemon" unistd.h)
(("cuserid" unistd.h stdio.h)
nil . nil) . (("dbopen" db.h sys/types.h limits.h fcntl.h)
nil . nil)) . (("difftime" time.h)
(("des_setparity" rpc/des_crypt.h)
nil . nil) . (("dirfd" sys/types.h dirent.h)
nil . nil))) . (("dlopen" dlfcn.h)
(("dlclose" dlfcn.h)
(("div" stdlib.h)
nil . nil) . (("dlerror" dlfcn.h)
nil . nil)) . (("dn_comp" arpa/nameser.h netinet/in.h resolv.h)
(("dlsym" dlfcn.h)
nil . nil) . nil)))) . (("endmntent" mntent.h stdio.h)
(("ecb_crypt" rpc/des_crypt.h)
(("dremf" math.h)
(("drand48_r" stdlib.h)
(("dprintf" stdio.h)
nil . nil) . (("drem" math.h)
nil . nil)) . (("dysize" time.h)
(("dreml" math.h)
nil . nil) . (("eaccess" unistd.h)
nil . nil))) . (("encrypt_r" crypt.h stdlib.h unistd.h)
(("ecvt_r" stdlib.h)
(("ecvt" stdlib.h)
nil . nil) . (("encrypt" unistd.h)
nil . nil)) . (("endfsent" fstab.h)
(("endaliasent" aliases.h)
nil . nil) . nil))) . (("envz_remove" envz.h)
(("envz_add" envz.h)
(("endrpcent" netdb.h)
(("endnetgrent" netdb.h)
nil . nil) . (("endttyent" ttyent.h)
nil . nil)) . (("envz_get" envz.h)
(("envz_entry" envz.h)
nil . nil) . (("envz_merge" envz.h)
nil . nil))) . (("epoll_ctl" sys/epoll.h)
(("epoll_create" sys/epoll.h)
(("envz_strip" envz.h)
nil . nil) . (("epoll_create1" sys/epoll.h)
nil . nil)) . (("epoll_wait" sys/epoll.h)
(("epoll_pwait" sys/epoll.h)
nil . nil) . nil))))))) . (("fopen" stdio.h)
(("fegetenv" fenv.h)
(("exp10f" math.h)
(("ether_ntoa_r" netinet/ether.h)
(("err" err.h)
(("erfcf" math.h)
(("erf" math.h)
(("erand48_r" stdlib.h)
nil . nil) . (("erfc" math.h)
nil . nil)) . (("erff" math.h)
(("erfcl" math.h)
nil . nil) . (("erfl" math.h)
nil . nil))) . (("ether_aton_r" netinet/ether.h)
(("errx" err.h)
(("errno" errno.h)
nil . nil) . (("ether_aton" netinet/ether.h)
nil . nil)) . (("ether_line" netinet/ether.h)
(("ether_hostton" netinet/ether.h)
nil . nil) . (("ether_ntoa" netinet/ether.h)
nil . nil)))) . (("execve" unistd.h)
(("execl" unistd.h)
(("euidaccess" unistd.h)
(("ether_ntohost" netinet/ether.h)
nil . nil) . (("eventfd" sys/eventfd.h)
nil . nil)) . (("execlp" unistd.h)
(("execle" unistd.h)
nil . nil) . (("execv" unistd.h)
nil . nil))) . (("exit_group" linux/unistd.h)
(("execvpe" unistd.h)
(("execvp" unistd.h)
nil . nil) . (("exit" stdlib.h)
nil . nil)) . (("exp10" math.h)
(("exp" math.h)
nil . nil) . nil)))) . (("fchmod" sys/stat.h)
(("expm1f" math.h)
(("exp2l" math.h)
(("exp2" math.h)
(("exp10l" math.h)
nil . nil) . (("exp2f" math.h)
nil . nil)) . (("expl" math.h)
(("expf" math.h)
nil . nil) . (("expm1" math.h)
nil . nil))) . (("fabsl" math.h)
(("fabs" math.h)
(("expm1l" math.h)
nil . nil) . (("fabsf" math.h)
nil . nil)) . (("fallocate" fcntl.h)
(("faccessat" unistd.h fcntl.h)
nil . nil) . (("fchdir" unistd.h)
nil . nil)))) . (("fdatasync" unistd.h)
(("fclose" stdio.h)
(("fchown" unistd.h)
(("fchmodat" sys/stat.h fcntl.h)
nil . nil) . (("fchownat" unistd.h fcntl.h)
nil . nil)) . (("fcvt" stdlib.h)
(("fcntl" unistd.h fcntl.h)
nil . nil) . (("fcvt_r" stdlib.h)
nil . nil))) . (("fdopen" stdio.h)
(("fdimf" math.h)
(("fdim" math.h)
nil . nil) . (("fdiml" math.h)
nil . nil)) . (("feclearexcept" fenv.h)
(("fdopendir" sys/types.h dirent.h)
nil . nil) . nil))))) . (("fgetss" wchar.h)
(("fflush_unlocked" stdio.h)
(("ferror_unlocked" stdio.h)
(("feof" stdio.h)
(("fegetround" fenv.h)
(("fegetexceptflag" fenv.h)
nil . nil) . (("feholdexcept" fenv.h)
nil . nil)) . (("feraiseexcept" fenv.h)
(("feof_unlocked" stdio.h)
nil . nil) . (("ferror" stdio.h)
nil . nil))) . (("fetestexcept" fenv.h)
(("fesetexceptflag" fenv.h)
(("fesetenv" fenv.h)
nil . nil) . (("fesetround" fenv.h)
nil . nil)) . (("fexecve" unistd.h)
(("feupdateenv" fenv.h)
nil . nil) . (("fflush" stdio.h)
nil . nil)))) . (("fgetpos" stdio.h)
(("fgetc" stdio.h)
(("ffsl" strings.h string.h)
(("ffs" strings.h)
nil . nil) . (("ffsll" strings.h string.h)
nil . nil)) . (("fgetgrent" sys/types.h stdio.h grp.h)
(("fgetc_unlocked" stdio.h)
nil . nil) . (("fgetgrent_r" grp.h)
nil . nil))) . (("fgets_unlocked" stdio.h)
(("fgetpwent_r" pwd.h)
(("fgetpwent" pwd.h sys/types.h stdio.h)
nil . nil) . (("fgets" stdio.h)
nil . nil)) . (("fgetspent_r" shadow.h)
(("fgetspent" shadow.h)
nil . nil) . nil)))) . (("fma" math.h)
(("finitef" math.h)
(("fgetws_unlocked" stdio.h wchar.h)
(("fgetwc_unlocked" stdio.h wchar.h)
(("fgetwc" wchar.h)
nil . nil) . (("fgetws" wchar.h)
nil . nil)) . (("fileno_unlocked" stdio.h)
(("fileno" stdio.h)
nil . nil) . (("finite" math.h)
nil . nil))) . (("floor" math.h)
(("flock" sys/file.h)
(("finitel" math.h)
nil . nil) . (("flockfile" stdio.h)
nil . nil)) . (("floorl" math.h)
(("floorf" math.h)
nil . nil) . nil))) . (("fminf" math.h)
(("fmaxf" math.h)
(("fmal" math.h)
(("fmaf" math.h)
nil . nil) . (("fmax" math.h)
nil . nil)) . (("fmemopen" stdio.h)
(("fmaxl" math.h)
nil . nil) . (("fmin" math.h)
nil . nil))) . (("fmodl" math.h)
(("fmod" math.h)
(("fminl" math.h)
nil . nil) . (("fmodf" math.h)
nil . nil)) . (("fnmatch" fnmatch.h)
(("fmtmsg" fmtmsg.h)
nil . nil) . nil)))))) . (("gammal" math.h)
(("fstatat" sys/stat.h fcntl.h)
(("fread" stdio.h)
(("fputc" stdio.h)
(("fpclassify" math.h)
(("forkpty" pty.h)
(("fopencookie" stdio.h)
nil . nil) . (("fpathconf" unistd.h)
nil . nil)) . (("fprintf" stdio.h)
(("fpos_t" stdio.h)
nil . nil) . (("fpurge" stdio.h)
nil . nil))) . (("fputwc" wchar.h)
(("fputs" stdio.h)
(("fputc_unlocked" stdio.h)
nil . nil) . (("fputs_unlocked" stdio.h)
nil . nil)) . (("fputws" wchar.h)
(("fputwc_unlocked" stdio.h wchar.h)
nil . nil) . (("fputws_unlocked" stdio.h wchar.h)
nil . nil)))) . (("frexpf" math.h)
(("freehostent" sys/socket.h sys/types.h netdb.h)
(("free" stdlib.h)
(("fread_unlocked" stdio.h)
nil . nil) . (("freeaddrinfo" sys/socket.h sys/types.h netdb.h)
nil . nil)) . (("freopen" stdio.h)
(("freeifaddrs" sys/types.h ifaddrs.h)
nil . nil) . (("frexp" math.h)
nil . nil))) . (("fseeko" stdio.h)
(("fscanf" stdio.h)
(("frexpl" math.h)
nil . nil) . (("fseek" stdio.h)
nil . nil)) . (("fstat" sys/stat.h unistd.h sys/types.h)
(("fsetpos" stdio.h)
nil . nil) . nil)))) . (("funlockfile" stdio.h)
(("ftruncate" unistd.h sys/types.h)
(("ftell" stdio.h)
(("fstatvfs" sys/statvfs.h)
(("fstatfs" sys/vfs.h)
nil . nil) . (("fsync" unistd.h)
nil . nil)) . (("ftime" sys/timeb.h)
(("ftello" stdio.h)
nil . nil) . (("ftok" sys/ipc.h sys/types.h)
nil . nil))) . (("fts_open" sys/stat.h fts.h sys/types.h)
(("fts_children" sys/stat.h fts.h sys/types.h)
(("ftrylockfile" stdio.h)
nil . nil) . (("fts_close" sys/stat.h fts.h sys/types.h)
nil . nil)) . (("fts_set" sys/stat.h fts.h sys/types.h)
(("fts_read" sys/stat.h fts.h sys/types.h)
nil . nil) . (("ftw" ftw.h)
nil . nil)))) . (("fwrite_unlocked" stdio.h)
(("futimesat" fcntl.h)
(("futimens" sys/stat.h)
(("futex" linux/futex.h sys/time.h)
nil . nil) . (("futimes" sys/time.h)
nil . nil)) . (("fwprintf" wchar.h)
(("fwide" wchar.h)
nil . nil) . (("fwrite" stdio.h)
nil . nil))) . (("gai_suspend" netdb.h)
(("gai_error" netdb.h)
(("gai_cancel" netdb.h)
nil . nil) . (("gai_strerror" sys/socket.h sys/types.h netdb.h)
nil . nil)) . (("gammaf" math.h)
(("gamma" math.h)
nil . nil) . nil))))) . (("getgrnam" sys/types.h grp.h)
(("getcontext" ucontext.h)
(("getaliasbyname" aliases.h)
(("get_mempolicy" numaif.h)
(("get_current_dir_name" unistd.h)
(("gcvt" stdlib.h)
nil . nil) . (("get_kernel_syms" linux/module.h)
nil . nil)) . (("getaddrinfo" sys/socket.h sys/types.h netdb.h)
(("get_thread_area" linux/unistd.h asm/ldt.h)
nil . nil) . (("getaddrinfo_a" netdb.h)
nil . nil))) . (("getc" stdio.h)
(("getaliasent" aliases.h)
(("getaliasbyname_r" aliases.h)
nil . nil) . (("getaliasent_r" aliases.h)
nil . nil)) . (("getchar" stdio.h)
(("getc_unlocked" stdio.h)
nil . nil) . (("getchar_unlocked" stdio.h)
nil . nil)))) . (("getenv" stdlib.h)
(("getdate_r" time.h)
(("getcwd" unistd.h)
(("getcpu" linux/getcpu.h)
nil . nil) . (("getdate" time.h)
nil . nil)) . (("getdirentries" dirent.h)
(("getdelim" stdio.h)
nil . nil) . (("getdomainname" unistd.h)
nil . nil))) . (("getgrent_r" grp.h)
(("getfsfile" fstab.h)
(("getfsent" fstab.h)
nil . nil) . (("getfsspec" fstab.h)
nil . nil)) . (("getgrgid_r" sys/types.h grp.h)
(("getgrgid" sys/types.h grp.h)
nil . nil) . nil)))) . (("getline" stdio.h)
(("gethostbyname_r" sys/socket.h netdb.h)
(("gethostbyaddr_r" sys/socket.h netdb.h)
(("getgrouplist" grp.h)
(("getgrnam_r" sys/types.h grp.h)
nil . nil) . (("gethostbyaddr" sys/socket.h netdb.h)
nil . nil)) . (("gethostbyname2" sys/socket.h netdb.h)
(("gethostbyname" netdb.h)
nil . nil) . (("gethostbyname2_r" sys/socket.h netdb.h)
nil . nil))) . (("getipnodebyaddr" sys/socket.h sys/types.h netdb.h)
(("gethostname" unistd.h)
(("gethostent_r" sys/socket.h netdb.h)
nil . nil) . (("getifaddrs" sys/types.h ifaddrs.h)
nil . nil)) . (("getitimer" sys/time.h)
(("getipnodebyname" sys/socket.h sys/types.h netdb.h)
nil . nil) . nil))) . (("getnetbyaddr_r" netdb.h)
(("getmntent" mntent.h stdio.h)
(("getlogin" unistd.h)
(("getloadavg" stdlib.h)
nil . nil) . (("getlogin_r" unistd.h)
nil . nil)) . (("getnameinfo" sys/socket.h netdb.h)
(("getmntent_r" mntent.h stdio.h)
nil . nil) . (("getnetbyaddr" netdb.h)
nil . nil))) . (("getnetgrent" netdb.h)
(("getnetbyname_r" netdb.h)
(("getnetbyname" netdb.h)
nil . nil) . (("getnetent_r" netdb.h)
nil . nil)) . (("getopt" unistd.h)
(("getnetgrent_r" netdb.h)
nil . nil) . nil))))))))) . (("raise" signal.h)
(("logbf" math.h)
(("intptr_t" stdint.h)
(("hasmntopt" mntent.h stdio.h)
(("getservbyname_r" netdb.h)
(("getpwnam_r" pwd.h sys/types.h)
(("getprotobyname_r" netdb.h)
(("getpgid" unistd.h)
(("getpass" unistd.h)
(("getopt_long_only" getopt.h unistd.h)
nil . nil) . (("getpeername" sys/socket.h)
nil . nil)) . (("getpriority" sys/resource.h sys/time.h)
(("getpgrp" unistd.h)
nil . nil) . (("getprotobyname" netdb.h)
nil . nil))) . (("getpt" stdlib.h)
(("getprotobynumber_r" netdb.h)
(("getprotobynumber" netdb.h)
nil . nil) . (("getprotoent_r" netdb.h)
nil . nil)) . (("getpwent_r" pwd.h)
(("getpw" pwd.h sys/types.h)
nil . nil) . (("getpwnam" pwd.h sys/types.h)
nil . nil)))) . (("getrpcbynumber" netdb.h)
(("getresuid" unistd.h)
(("getpwuid_r" pwd.h sys/types.h)
(("getpwuid" pwd.h sys/types.h)
nil . nil) . (("getresgid" unistd.h)
nil . nil)) . (("getrpcbyname" netdb.h)
(("getrlimit" sys/resource.h sys/time.h)
nil . nil) . (("getrpcbyname_r" netdb.h)
nil . nil))) . (("getrusage" sys/resource.h sys/time.h)
(("getrpcent" netdb.h)
(("getrpcbynumber_r" netdb.h)
nil . nil) . (("getrpcent_r" netdb.h)
nil . nil)) . (("getservbyname" netdb.h)
(("gets" stdio.h)
nil . nil) . nil)))) . (("getutline" utmp.h)
(("getspnam" shadow.h)
(("getsid" unistd.h)
(("getservbyport_r" netdb.h)
(("getservbyport" netdb.h)
nil . nil) . (("getservent_r" netdb.h)
nil . nil)) . (("getsockopt" sys/socket.h sys/types.h)
(("getsockname" sys/socket.h)
nil . nil) . (("getspent_r" shadow.h)
nil . nil))) . (("getttyent" ttyent.h)
(("getsubopt" stdlib.h)
(("getspnam_r" shadow.h)
nil . nil) . (("gettimeofday" sys/time.h)
nil . nil)) . (("getumask" sys/stat.h sys/types.h)
(("getttynam" ttyent.h)
nil . nil) . (("getutid" utmp.h)
nil . nil)))) . (("getwd" unistd.h)
(("getwc" stdio.h wchar.h)
(("getutmpx" utmpx.h)
(("getutmp" utmpx.h)
nil . nil) . (("getw" stdio.h)
nil . nil)) . (("getwchar" wchar.h)
(("getwc_unlocked" stdio.h wchar.h)
nil . nil) . (("getwchar_unlocked" stdio.h wchar.h)
nil . nil))) . (("gmtime_r" time.h)
(("globfree" glob.h)
(("glob" glob.h)
nil . nil) . (("gmtime" time.h)
nil . nil)) . (("gsignal" signal.h)
(("grantpt" stdlib.h)
nil . nil) . nil))))) . (("inet_lnaof" arpa/inet.h sys/socket.h netinet/in.h)
(("htons" arpa/inet.h)
(("hstrerror" sys/socket.h netdb.h)
(("hdestroy_r" search.h)
(("hcreate_r" search.h)
(("hcreate" search.h)
nil . nil) . (("hdestroy" search.h)
nil . nil)) . (("hsearch" search.h)
(("herror" sys/socket.h netdb.h)
nil . nil) . (("hsearch_r" search.h)
nil . nil))) . (("htole16" endian.h)
(("htobe32" endian.h)
(("htobe16" endian.h)
nil . nil) . (("htobe64" endian.h)
nil . nil)) . (("htole64" endian.h)
(("htole32" endian.h)
nil . nil) . (("htonl" arpa/inet.h)
nil . nil)))) . (("ilogbf" math.h)
(("iconv" iconv.h)
(("hypotf" math.h)
(("hypot" math.h)
nil . nil) . (("hypotl" math.h)
nil . nil)) . (("iconv_open" iconv.h)
(("iconv_close" iconv.h)
nil . nil) . (("ilogb" math.h)
nil . nil))) . (("index" strings.h)
(("imaxabs" stdlib.h inttypes.h)
(("ilogbl" math.h)
nil . nil) . (("imaxdiv" stdlib.h inttypes.h)
nil . nil)) . (("inet_aton" arpa/inet.h sys/socket.h netinet/in.h)
(("inet_addr" arpa/inet.h sys/socket.h netinet/in.h)
nil . nil) . nil)))) . (("insque" search.h)
(("initgroups" sys/types.h grp.h)
(("inet_ntoa" arpa/inet.h sys/socket.h netinet/in.h)
(("inet_netof" arpa/inet.h sys/socket.h netinet/in.h)
(("inet_makeaddr" arpa/inet.h sys/socket.h netinet/in.h)
nil . nil) . (("inet_network" arpa/inet.h sys/socket.h netinet/in.h)
nil . nil)) . (("inet_pton" arpa/inet.h)
(("inet_ntop" arpa/inet.h)
nil . nil) . (("init_module" linux/module.h)
nil . nil))) . (("inotify_add_watch" sys/inotify.h)
(("initstate_r" stdlib.h)
(("initstate" stdlib.h)
nil . nil) . (("innetgr" netdb.h)
nil . nil)) . (("inotify_init1" sys/inotify.h)
(("inotify_init" sys/inotify.h)
nil . nil) . (("inotify_rm_watch" sys/inotify.h)
nil . nil)))) . (("int_fast64_t" stdint.h)
(("int64_t" stdint.h)
(("int16_t" stdint.h)
(("int" search.h)
nil . nil) . (("int32_t" stdint.h)
nil . nil)) . (("int_fast16_t" stdint.h)
(("int8_t" stdint.h)
nil . nil) . (("int_fast32_t" stdint.h)
nil . nil))) . (("int_least64_t" stdint.h)
(("int_least16_t" stdint.h)
(("int_fast8_t" stdint.h)
nil . nil) . (("int_least32_t" stdint.h)
nil . nil)) . (("intmax_t" stdint.h)
(("int_least8_t" stdint.h)
nil . nil) . nil)))))) . (("jrand48_r" stdlib.h)
(("isnormal" math.h)
(("isdigit" ctype.h)
(("iopl" sys/io.h)
(("io_setup" libaio.h)
(("io_destroy" libaio.h)
(("io_cancel" libaio.h)
nil . nil) . (("io_getevents" linux/time.h libaio.h)
nil . nil)) . (("ioctl" sys/ioctl.h)
(("io_submit" libaio.h)
nil . nil) . (("ioperm" unistd.h sys/io.h)
nil . nil))) . (("isascii" ctype.h)
(("isalnum" ctype.h)
(("iruserok" netdb.h)
nil . nil) . (("isalpha" ctype.h)
nil . nil)) . (("isblank" ctype.h)
(("isatty" unistd.h)
nil . nil) . (("iscntrl" ctype.h)
nil . nil)))) . (("isless" math.h)
(("isgreaterequal" math.h)
(("isgraph" ctype.h)
(("isfinite" math.h)
nil . nil) . (("isgreater" math.h)
nil . nil)) . (("isinff" math.h)
(("isinf" math.h)
nil . nil) . (("isinfl" math.h)
nil . nil))) . (("isnan" math.h)
(("islessgreater" math.h)
(("islessequal" math.h)
nil . nil) . (("islower" ctype.h)
nil . nil)) . (("isnanl" math.h)
(("isnanf" math.h)
nil . nil) . nil)))) . (("iswspace" wctype.h)
(("iswblank" wctype.h)
(("isunordered" math.h)
(("ispunct" ctype.h)
(("isprint" cctype)
nil . nil) . (("isspace" ctype.h)
nil . nil)) . (("iswalnum" wctype.h)
(("isupper" ctype.h)
nil . nil) . (("iswalpha" wctype.h)
nil . nil))) . (("iswgraph" wctype.h)
(("iswctype" wctype.h)
(("iswcntrl" wctype.h)
nil . nil) . (("iswdigit" wctype.h)
nil . nil)) . (("iswprint" wctype.h)
(("iswlower" wctype.h)
nil . nil) . (("iswpunct" wctype.h)
nil . nil)))) . (("j1f" math.h)
(("j0" math.h)
(("iswxdigit" wctype.h)
(("iswupper" wctype.h)
nil . nil) . (("isxdigit" ctype.h)
nil . nil)) . (("j0l" math.h)
(("j0f" math.h)
nil . nil) . (("j1" math.h)
nil . nil))) . (("jnf" math.h)
(("jmp_buf" setjmp.h)
(("j1l" math.h)
nil . nil) . (("jn" math.h)
nil . nil)) . (("jrand48" stdlib.h)
(("jnl" math.h)
nil . nil) . nil))))) . (("lgammal_r" math.h)
(("lcong48_r" stdlib.h)
(("kill" sys/types.h signal.h)
(("key_gendes" rpc/rpc.h)
(("key_decryptsession" rpc/rpc.h)
(("kexec_load" linux/kexec.h)
nil . nil) . (("key_encryptsession" rpc/rpc.h)
nil . nil)) . (("key_setsecret" rpc/rpc.h)
(("key_secretkey_is_set" rpc/rpc.h)
nil . nil) . (("keyctl" keyutils.h)
nil . nil))) . (("l64a" stdlib.h)
(("killpg" signal.h)
(("kill_dependency" stdatomic.h)
nil . nil) . (("klogctl" sys/klog.h)
nil . nil)) . (("lchown" unistd.h)
(("labs" stdlib.h)
nil . nil) . (("lcong48" stdlib.h)
nil . nil)))) . (("le64toh" endian.h)
(("ldexpl" math.h)
(("ldexp" math.h)
(("lconv" locale.h)
nil . nil) . (("ldexpf" math.h)
nil . nil)) . (("le16toh" endian.h)
(("ldiv" stdlib.h)
nil . nil) . (("le32toh" endian.h)
nil . nil))) . (("lgammaf" math.h)
(("lgamma" math.h)
(("lfind" search.h)
nil . nil) . (("lgamma_r" math.h)
nil . nil)) . (("lgammal" math.h)
(("lgammaf_r" math.h)
nil . nil) . nil)))) . (("localeconv" locale.h)
(("lldiv" stdlib.h)
(("linkat" unistd.h fcntl.h)
(("libtasn1_strerror" libtasn1.h)
(("libtasn1_perror" libtasn1.h)
nil . nil) . (("link" unistd.h)
nil . nil)) . (("listen" sys/socket.h sys/types.h)
(("lio_listio" aio.h)
nil . nil) . (("llabs" stdlib.h)
nil . nil))) . (("llround" math.h)
(("llrintf" math.h)
(("llrint" math.h)
nil . nil) . (("llrintl" math.h)
nil . nil)) . (("llroundl" math.h)
(("llroundf" math.h)
nil . nil) . nil))) . (("log1p" math.h)
(("log" math.h)
(("localtime_r" time.h)
(("localtime" time.h)
nil . nil) . (("lockf" unistd.h)
nil . nil)) . (("log10f" math.h)
(("log10" math.h)
nil . nil) . (("log10l" math.h)
nil . nil))) . (("log2f" math.h)
(("log1pl" math.h)
(("log1pf" math.h)
nil . nil) . (("log2" math.h)
nil . nil)) . (("logb" math.h)
(("log2l" math.h)
nil . nil) . nil))))))) . (("nexttowardf" math.h)
(("mkstemp" stdlib.h)
(("mbrtoc32" cuchar)
(("lsearch" search.h)
(("longjmp" setjmp.h)
(("login_tty" utmp.h pty.h)
(("logf" math.h)
(("logbl" math.h)
nil . nil) . (("login" utmp.h)
nil . nil)) . (("logout" utmp.h)
(("logl" math.h)
nil . nil) . (("logwtmp" utmp.h)
nil . nil))) . (("lrintl" math.h)
(("lrint" math.h)
(("lrand48_r" stdlib.h)
nil . nil) . (("lrintf" math.h)
nil . nil)) . (("lroundf" math.h)
(("lround" math.h)
nil . nil) . (("lroundl" math.h)
nil . nil)))) . (("makedev" sys/types.h)
(("lutimes" sys/time.h)
(("lseek64" unistd.h sys/types.h)
(("lseek" unistd.h sys/types.h)
nil . nil) . (("lstat" sys/stat.h unistd.h sys/types.h)
nil . nil)) . (("major" sys/types.h)
(("madvise" sys/mman.h)
nil . nil) . (("makecontext" ucontext.h)
nil . nil))) . (("mblen" stdlib.h)
(("matherr" math.h)
(("malloc" stdlib.h)
nil . nil) . (("mbind" numaif.h)
nil . nil)) . (("mbrtoc16" uchar.h)
(("mbrlen" wchar.h)
nil . nil) . nil)))) . (("mempcpy" string.h)
(("memalign" stdlib.h malloc.h)
(("mbsrtowcs" wchar.h)
(("mbsinit" wchar.h)
(("mbrtowc" wchar.h)
nil . nil) . (("mbsnrtowcs" wchar.h)
nil . nil)) . (("mbstowcs" stdlib.h)
(("mbstate_t" wchar.h)
nil . nil) . (("mbtowc" stdlib.h)
nil . nil))) . (("memcpy" string.h)
(("memchr" string.h)
(("memccpy" string.h)
nil . nil) . (("memcmp" string.h)
nil . nil)) . (("memmem" string.h)
(("memfrob" string.h)
nil . nil) . (("memmove" string.h)
nil . nil)))) . (("mkdtemp" stdlib.h)
(("mincore" sys/mman.h unistd.h)
(("memset" string.h)
(("memrchr" string.h)
nil . nil) . (("migrate_pages" numaif.h)
nil . nil)) . (("mkdir" sys/stat.h sys/types.h)
(("minor" sys/types.h)
nil . nil) . (("mkdirat" sys/stat.h fcntl.h)
nil . nil))) . (("mknodat" sys/stat.h fcntl.h)
(("mkfifoat" sys/stat.h fcntl.h)
(("mkfifo" sys/stat.h sys/types.h)
nil . nil) . (("mknod" sys/stat.h sys/types.h unistd.h fcntl.h)
nil . nil)) . (("mkostemps" stdlib.h)
(("mkostemp" stdlib.h)
nil . nil) . nil))))) . (("mq_timedsend" mqueue.h time.h)
(("mpool_get" db.h mpool.h)
(("modf" math.h)
(("mlock" sys/mman.h)
(("mktemp" stdlib.h)
(("mkstemps" stdlib.h)
nil . nil) . (("mktime" time.h)
nil . nil)) . (("mmap" sys/mman.h)
(("mlockall" sys/mman.h)
nil . nil) . (("mmap2" sys/mman.h)
nil . nil))) . (("mount" sys/mount.h)
(("modfl" math.h)
(("modff" math.h)
nil . nil) . (("modify_ldt" sys/types.h)
nil . nil)) . (("mpool_close" db.h mpool.h)
(("move_pages" numaif.h)
nil . nil) . (("mpool_filter" db.h mpool.h)
nil . nil)))) . (("mq_getsetattr" mqueue.h sys/types.h)
(("mpool_sync" db.h mpool.h)
(("mpool_open" db.h mpool.h)
(("mpool_new" db.h mpool.h)
nil . nil) . (("mpool_put" db.h mpool.h)
nil . nil)) . (("mq_close" mqueue.h)
(("mprotect" sys/mman.h)
nil . nil) . (("mq_getattr" mqueue.h)
nil . nil))) . (("mq_send" mqueue.h)
(("mq_open" sys/stat.h mqueue.h fcntl.h)
(("mq_notify" mqueue.h)
nil . nil) . (("mq_receive" mqueue.h)
nil . nil)) . (("mq_timedreceive" mqueue.h time.h)
(("mq_setattr" mqueue.h)
nil . nil) . nil)))) . (("mtx_unlock" threads.h)
(("msync" sys/mman.h)
(("msgctl" sys/msg.h sys/ipc.h sys/types.h)
(("mrand48_r" stdlib.h)
(("mq_unlink" mqueue.h)
nil . nil) . (("mremap" sys/mman.h)
nil . nil)) . (("msgrcv" sys/msg.h sys/ipc.h sys/types.h)
(("msgget" sys/msg.h sys/ipc.h sys/types.h)
nil . nil) . (("msgsnd" sys/msg.h sys/ipc.h sys/types.h)
nil . nil))) . (("mtx_lock" threads.h)
(("mtx_destroy" threads.h)
(("mtrace" mcheck.h)
nil . nil) . (("mtx_init" threads.h)
nil . nil)) . (("mtx_trylock" threads.h)
(("mtx_t" threads.h)
nil . nil) . nil))) . (("nearbyint" math.h)
(("nan" math.h)
(("munmap" sys/mman.h)
(("munlock" sys/mman.h)
nil . nil) . (("muntrace" mcheck.h)
nil . nil)) . (("nanl" math.h)
(("nanf" math.h)
nil . nil) . (("nanosleep" time.h)
nil . nil))) . (("nextafterf" math.h)
(("nearbyintl" math.h)
(("nearbyintf" math.h)
nil . nil) . (("nextafter" math.h)
nil . nil)) . (("nexttoward" math.h)
(("nextafterl" math.h)
nil . nil) . nil)))))) . (("pthread_attr_setaffinity_np" pthread.h)
(("posix_fallocate" fcntl.h)
(("openat" fcntl.h)
(("ntohl" arpa/inet.h)
(("nice" unistd.h)
(("nfsservctl" linux/nfsd/syscall.h)
(("nexttowardl" math.h)
nil . nil) . (("nftw" ftw.h)
nil . nil)) . (("nrand48" stdlib.h)
(("nl_langinfo" langinfo.h)
nil . nil) . (("nrand48_r" stdlib.h)
nil . nil))) . (("once_flag" threads.h)
(("offsetof" stddef.h)
(("ntohs" arpa/inet.h)
nil . nil) . (("on_exit" stdlib.h)
nil . nil)) . (("open_memstream" stdio.h)
(("open" sys/stat.h sys/types.h fcntl.h)
nil . nil) . (("open_wmemstream" stdio.h wchar.h)
nil . nil)))) . (("pciconfig_write" pci.h)
(("passwd2des" rpc/des_crypt.h)
(("openlog" syslog.h)
(("opendir" sys/types.h dirent.h)
nil . nil) . (("openpty" pty.h)
nil . nil)) . (("pciconfig_iobase" pci.h)
(("pathconf" unistd.h)
nil . nil) . (("pciconfig_read" pci.h)
nil . nil))) . (("poll" poll.h)
(("perror" stdio.h)
(("pclose" stdio.h)
nil . nil) . (("personality" sys/personality.h)
nil . nil)) . (("posix_fadvise" fcntl.h)
(("popen" stdio.h)
nil . nil) . nil)))) . (("pselect" sys/select.h unistd.h sys/types.h sys/time.h)
(("powl" math.h)
(("pow10" math.h)
(("posix_openpt" stdlib.h fcntl.h)
(("posix_memalign" stdlib.h)
nil . nil) . (("pow" math.h)
nil . nil)) . (("pow10l" math.h)
(("pow10f" math.h)
nil . nil) . (("powf" math.h)
nil . nil))) . (("preadv" sys/uio.h)
(("prctl" sys/prctl.h)
(("ppoll" poll.h)
nil . nil) . (("pread" unistd.h)
nil . nil)) . (("prlimit" sys/resource.h sys/time.h)
(("printf" stdio.h)
nil . nil) . (("profil" unistd.h)
nil . nil)))) . (("pthread_attr_getschedparam" pthread.h)
(("pthread_attr_getaffinity_np" pthread.h)
(("psignal" signal.h)
(("psiginfo" signal.h)
nil . nil) . (("pthread_attr_destroy" pthread.h)
nil . nil)) . (("pthread_attr_getguardsize" pthread.h)
(("pthread_attr_getdetachstate" pthread.h)
nil . nil) . (("pthread_attr_getinheritsched" pthread.h)
nil . nil))) . (("pthread_attr_getstackaddr" pthread.h)
(("pthread_attr_getscope" pthread.h)
(("pthread_attr_getschedpolicy" pthread.h)
nil . nil) . (("pthread_attr_getstack" pthread.h)
nil . nil)) . (("pthread_attr_init" pthread.h)
(("pthread_attr_getstacksize" pthread.h)
nil . nil) . nil))))) . (("pthread_timedjoin_np" pthread.h)
(("pthread_detach" pthread.h)
(("pthread_attr_setstackaddr" pthread.h)
(("pthread_attr_setschedparam" pthread.h)
(("pthread_attr_setguardsize" pthread.h)
(("pthread_attr_setdetachstate" pthread.h)
nil . nil) . (("pthread_attr_setinheritsched" pthread.h)
nil . nil)) . (("pthread_attr_setscope" pthread.h)
(("pthread_attr_setschedpolicy" pthread.h)
nil . nil) . (("pthread_attr_setstack" pthread.h)
nil . nil))) . (("pthread_cleanup_pop_restore_np" pthread.h)
(("pthread_cancel" pthread.h)
(("pthread_attr_setstacksize" pthread.h)
nil . nil) . (("pthread_cleanup_pop" pthread.h)
nil . nil)) . (("pthread_cleanup_push_defer_np" pthread.h)
(("pthread_cleanup_push" pthread.h)
nil . nil) . (("pthread_create" pthread.h)
nil . nil)))) . (("pthread_kill" signal.h)
(("pthread_getattr_np" pthread.h)
(("pthread_exit" pthread.h)
(("pthread_equal" pthread.h)
nil . nil) . (("pthread_getaffinity_np" pthread.h)
nil . nil)) . (("pthread_getcpuclockid" pthread.h time.h)
(("pthread_getconcurrency" pthread.h)
nil . nil) . (("pthread_join" pthread.h)
nil . nil))) . (("pthread_setconcurrency" pthread.h)
(("pthread_setcancelstate" pthread.h)
(("pthread_setaffinity_np" pthread.h)
nil . nil) . (("pthread_setcanceltype" pthread.h)
nil . nil)) . (("pthread_sigqueue" pthread.h)
(("pthread_sigmask" signal.h)
nil . nil) . nil)))) . (("putw" stdio.h)
(("putchar_unlocked" stdio.h)
(("ptsname_r" stdlib.h)
(("ptrace" sys/ptrace.h)
(("pthread_tryjoin_np" pthread.h)
nil . nil) . (("ptsname" stdlib.h)
nil . nil)) . (("putc_unlocked" stdio.h)
(("putc" stdio.h)
nil . nil) . (("putchar" stdio.h)
nil . nil))) . (("puts" stdio.h)
(("putgrent" grp.h)
(("putenv" stdlib.h)
nil . nil) . (("putpwent" pwd.h sys/types.h stdio.h)
nil . nil)) . (("pututline" utmp.h)
(("putspent" shadow.h)
nil . nil) . nil))) . (("qecvt_r" stdlib.h)
(("putwchar_unlocked" stdio.h wchar.h)
(("putwc_unlocked" stdio.h wchar.h)
(("putwc" stdio.h wchar.h)
nil . nil) . (("putwchar" wchar.h)
nil . nil)) . (("pwritev" sys/uio.h)
(("pwrite" unistd.h)
nil . nil) . (("qecvt" stdlib.h)
nil . nil))) . (("qsort" stdlib.h)
(("qfcvt_r" stdlib.h)
(("qfcvt" stdlib.h)
nil . nil) . (("qgcvt" stdlib.h)
nil . nil)) . (("quotactl" xfs/xqm.h sys/quota.h)
(("quick_exit" stdlib.h)
nil . nil) . nil)))))))) . (("strnlen" string.h)
(("setmntent" mntent.h stdio.h)
(("scalblnl" math.h)
(("remquof" math.h)
(("reboot" unistd.h linux/reboot.h)
(("readahead" fcntl.h)
(("rcmd" netdb.h)
(("random_r" stdlib.h)
(("rand_r" stdlib.h)
nil . nil) . (("rawmemchr" string.h)
nil . nil)) . (("re_exec" sys/types.h regex.h)
(("re_comp" sys/types.h regex.h)
nil . nil) . (("read" unistd.h)
nil . nil))) . (("readlinkat" unistd.h fcntl.h)
(("readdir_r" dirent.h)
(("readdir" dirent.h)
nil . nil) . (("readlink" unistd.h)
nil . nil)) . (("realloc" stdlib.h)
(("readv" sys/uio.h)
nil . nil) . (("realpath" limits.h stdlib.h)
nil . nil)))) . (("remainder" math.h)
(("regcomp" sys/types.h regex.h)
(("recvfrom" sys/socket.h sys/types.h)
(("recv" sys/socket.h sys/types.h)
nil . nil) . (("recvmsg" sys/socket.h sys/types.h)
nil . nil)) . (("regexec" sys/types.h regex.h)
(("regerror" sys/types.h regex.h)
nil . nil) . (("regfree" sys/types.h regex.h)
nil . nil))) . (("remove" stdio.h)
(("remainderl" math.h)
(("remainderf" math.h)
nil . nil) . (("remap_file_pages" sys/mman.h)
nil . nil)) . (("remquo" math.h)
(("remque" search.h)
nil . nil) . nil)))) . (("rintl" math.h)
(("res_search" arpa/nameser.h netinet/in.h resolv.h)
(("request_key" keyutils.h)
(("rename" stdio.h)
(("remquol" math.h)
nil . nil) . (("renameat" fcntl.h stdio.h)
nil . nil)) . (("res_query" arpa/nameser.h netinet/in.h resolv.h)
(("res_mkquery" arpa/nameser.h netinet/in.h resolv.h)
nil . nil) . (("res_querydomain" arpa/nameser.h netinet/in.h resolv.h)
nil . nil))) . (("rexec" netdb.h)
(("rewind" stdio.h)
(("res_send" arpa/nameser.h netinet/in.h resolv.h)
nil . nil) . (("rewinddir" sys/types.h dirent.h)
nil . nil)) . (("rint" math.h)
(("rindex" strings.h)
nil . nil) . (("rintf" math.h)
nil . nil)))) . (("ruserok" netdb.h)
(("roundl" math.h)
(("round" math.h)
(("rmdir" unistd.h)
nil . nil) . (("roundf" math.h)
nil . nil)) . (("rresvport" netdb.h)
(("rpmatch" stdlib.h)
nil . nil) . (("rtime" rpc/des_crypt.h)
nil . nil))) . (("scalbl" math.h)
(("scalb" math.h)
(("sbrk" unistd.h)
nil . nil) . (("scalbf" math.h)
nil . nil)) . (("scalblnf" math.h)
(("scalbln" cmath)
nil . nil) . nil))))) . (("semop" sys/sem.h sys/ipc.h sys/types.h)
(("seed48_r" stdlib.h)
(("sched_getaffinity" sched.h)
(("scandir" dirent.h)
(("scalbnf" math.h)
(("scalbn" cmath)
nil . nil) . (("scalbnl" math.h)
nil . nil)) . (("sched_get_priority_max" sched.h)
(("scanf" stdio.h)
nil . nil) . (("sched_get_priority_min" sched.h)
nil . nil))) . (("sched_setaffinity" sched.h)
(("sched_getscheduler" sched.h)
(("sched_getparam" sched.h)
nil . nil) . (("sched_rr_get_interval" sched.h)
nil . nil)) . (("sched_setscheduler" sched.h)
(("sched_setparam" sched.h)
nil . nil) . (("seed48" stdlib.h)
nil . nil)))) . (("sem_post" semaphore.h)
(("sem_destroy" semaphore.h)
(("select" sys/select.h unistd.h sys/types.h sys/time.h)
(("seekdir" dirent.h)
nil . nil) . (("sem_close" semaphore.h)
nil . nil)) . (("sem_init" semaphore.h)
(("sem_getvalue" semaphore.h)
nil . nil) . (("sem_open" sys/stat.h fcntl.h semaphore.h)
nil . nil))) . (("sem_wait" semaphore.h)
(("sem_trywait" semaphore.h)
(("sem_timedwait" semaphore.h)
nil . nil) . (("sem_unlink" semaphore.h)
nil . nil)) . (("semget" sys/sem.h sys/ipc.h sys/types.h)
(("semctl" sys/sem.h sys/ipc.h sys/types.h)
nil . nil) . nil)))) . (("seteuid" unistd.h sys/types.h)
(("setaliasent" aliases.h)
(("sendmsg" sys/socket.h sys/types.h)
(("send" sys/socket.h sys/types.h)
(("semtimedop" sys/sem.h sys/ipc.h sys/types.h)
nil . nil) . (("sendfile" sys/sendfile.h)
nil . nil)) . (("set_thread_area" linux/unistd.h asm/ldt.h)
(("sendto" sys/socket.h sys/types.h)
nil . nil) . (("set_tid_address" linux/unistd.h)
nil . nil))) . (("setdomainname" unistd.h)
(("setbuffer" stdio.h)
(("setbuf" stdio.h)
nil . nil) . (("setcontext" ucontext.h)
nil . nil)) . (("setenv" stdlib.h)
(("setegid" unistd.h sys/types.h)
nil . nil) . nil))) . (("setitimer" sys/time.h)
(("setgid" unistd.h sys/types.h)
(("setfsgid" unistd.h)
(("setfsent" fstab.h)
nil . nil) . (("setfsuid" unistd.h)
nil . nil)) . (("sethostid" unistd.h)
(("sethostent" sys/socket.h netdb.h)
nil . nil) . (("sethostname" unistd.h)
nil . nil))) . (("setlinebuf" stdio.h)
(("setkey" stdlib.h unistd.h)
(("setjmp" setjmp.h)
nil . nil) . (("setkey_r" crypt.h stdlib.h unistd.h)
nil . nil)) . (("setlogmask" syslog.h)
(("setlocale" locale.h)
nil . nil) . nil)))))) . (("sigwaitinfo" signal.h)
(("sig_atomic_t" signal.h)
(("setstate" stdlib.h)
(("setregid" unistd.h sys/types.h)
(("setpgid" unistd.h)
(("setnetgrent" netdb.h)
(("setnetent" netdb.h)
nil . nil) . (("setns" sched.h)
nil . nil)) . (("setpriority" sys/resource.h sys/time.h)
(("setpgrp" unistd.h)
nil . nil) . (("setprotoent" netdb.h)
nil . nil))) . (("setrlimit" sys/resource.h sys/time.h)
(("setresuid" unistd.h)
(("setresgid" unistd.h)
nil . nil) . (("setreuid" unistd.h sys/types.h)
nil . nil)) . (("setservent" netdb.h)
(("setrpcent" netdb.h)
nil . nil) . (("setsockopt" sys/socket.h sys/types.h)
nil . nil)))) . (("shm_open" sys/stat.h sys/mman.h fcntl.h)
(("setuid" unistd.h sys/types.h)
(("settimeofday" sys/time.h)
(("setstate_r" stdlib.h)
nil . nil) . (("setttyent" ttyent.h)
nil . nil)) . (("sgetspent" shadow.h)
(("setvbuf" stdio.h)
nil . nil) . (("sgetspent_r" shadow.h)
nil . nil))) . (("shmdt" sys/types.h sys/shm.h)
(("shmat" sys/types.h sys/shm.h)
(("shm_unlink" sys/stat.h sys/mman.h fcntl.h)
nil . nil) . (("shmctl" sys/ipc.h sys/shm.h)
nil . nil)) . (("shutdown" sys/socket.h)
(("shmget" sys/ipc.h sys/shm.h)
nil . nil) . nil)))) . (("signbit" math.h)
(("sighold" signal.h)
(("sigblock" signal.h)
(("sigaddset" signal.h)
(("sigaction" signal.h)
nil . nil) . (("sigaltstack" signal.h)
nil . nil)) . (("sigemptyset" signal.h)
(("sigdelset" signal.h)
nil . nil) . (("sigfillset" signal.h)
nil . nil))) . (("siglongjmp" setjmp.h)
(("siginterrupt" signal.h)
(("sigignore" signal.h)
nil . nil) . (("sigismember" signal.h)
nil . nil)) . (("signal" signal.h)
(("sigmask" signal.h)
nil . nil) . (("signalfd" sys/signalfd.h)
nil . nil)))) . (("sigrelse" signal.h)
(("sigpause" signal.h)
(("significandf" math.h)
(("significand" math.h)
nil . nil) . (("significandl" math.h)
nil . nil)) . (("sigprocmask" signal.h)
(("sigpending" signal.h)
nil . nil) . (("sigqueue" signal.h)
nil . nil))) . (("sigsuspend" signal.h)
(("sigsetjmp" setjmp.h)
(("sigset" signal.h)
nil . nil) . (("sigsetmask" signal.h)
nil . nil)) . (("sigvec" signal.h)
(("sigtimedwait" signal.h)
nil . nil) . nil))))) . (("statvfs" sys/statvfs.h)
(("sprintf" stdio.h)
(("sinhl" math.h)
(("sincosl" math.h)
(("sincos" math.h)
(("sin" math.h)
nil . nil) . (("sincosf" math.h)
nil . nil)) . (("sinh" math.h)
(("sinf" math.h)
nil . nil) . (("sinhf" math.h)
nil . nil))) . (("sockatmark" sys/socket.h)
(("sleep" unistd.h)
(("sinl" math.h)
nil . nil) . (("snprintf" stdio.h)
nil . nil)) . (("socketpair" sys/socket.h sys/types.h)
(("socket" linux/rtnetlink.h sys/socket.h asm/types.h linux/netlink.h)
nil . nil) . (("splice" fcntl.h)
nil . nil)))) . (("srand48_r" stdlib.h)
(("sqrtf" math.h)
(("spu_run" sys/spu.h)
(("spu_create" sys/types.h sys/spu.h)
nil . nil) . (("sqrt" math.h)
nil . nil)) . (("srand" stdlib.h)
(("sqrtl" math.h)
nil . nil) . (("srand48" stdlib.h)
nil . nil))) . (("ssignal" signal.h)
(("srandom_r" stdlib.h)
(("srandom" stdlib.h)
nil . nil) . (("sscanf" stdio.h)
nil . nil)) . (("statfs" sys/vfs.h)
(("stat" sys/stat.h unistd.h sys/types.h)
nil . nil) . nil)))) . (("strcspn" string.h)
(("strcasestr" string.h)
(("stime" time.h)
(("stdin" stdio.h)
(("stderr" stdio.h)
nil . nil) . (("stdout" stdio.h)
nil . nil)) . (("stpncpy" string.h)
(("stpcpy" string.h)
nil . nil) . (("strcasecmp" strings.h)
nil . nil))) . (("strcmp" string.h)
(("strchr" string.h)
(("strcat" string.h)
nil . nil) . (("strchrnul" string.h)
nil . nil)) . (("strcpy" string.h)
(("strcoll" string.h)
nil . nil) . nil))) . (("strlen" string.h)
(("strerror_r" string.h)
(("strdupa" string.h)
(("strdup" string.h)
nil . nil) . (("strerror" string.h)
nil . nil)) . (("strfry" string.h)
(("strfmon" monetary.h)
nil . nil) . (("strftime" time.h)
nil . nil))) . (("strncpy" string.h)
(("strncat" string)
(("strncasecmp" strings.h)
nil . nil) . (("strncmp" string.h)
nil . nil)) . (("strndupa" string.h)
(("strndup" string.h)
nil . nil) . nil))))))) . (("uint_least16_t" stdint.h)
(("thrd_current" threads.h)
(("sysconf" unistd.h)
(("strtoul" stdlib.h)
(("strtod" stdlib.h)
(("strsep" strings.h string.h)
(("strptime" time.h)
(("strpbrk" string.h)
nil . nil) . (("strrchr" string.h)
nil . nil)) . (("strspn" string.h)
(("strsignal" string.h)
nil . nil) . (("strstr" string.h)
nil . nil))) . (("strtok_r" string.h)
(("strtoimax" inttypes.h)
(("strtof" stdlib.h)
nil . nil) . (("strtok" string.h)
nil . nil)) . (("strtold" stdlib.h)
(("strtol" stdlib.h)
nil . nil) . (("strtoll" stdlib.h)
nil . nil)))) . (("swapon" sys/swap.h unistd.h asm/page.h)
(("strxfrm" string.h)
(("strtoumax" inttypes.h)
(("strtoull" stdlib.h)
nil . nil) . (("strverscmp" string.h)
nil . nil)) . (("swapcontext" ucontext.h)
(("swab" unistd.h)
nil . nil) . (("swapoff" sys/swap.h unistd.h asm/page.h)
nil . nil))) . (("sync_file_range" fcntl.h)
(("symlink" unistd.h)
(("swprintf" wchar.h)
nil . nil) . (("symlinkat" fcntl.h stdio.h)
nil . nil)) . (("syscall" unistd.h sys/syscall.h)
(("syncfs" unistd.h)
nil . nil) . nil)))) . (("tcgetsid" termios.h)
(("tanhf" math.h)
(("sysv_signal" signal.h)
(("syslog" syslog.h)
(("sysinfo" sys/sysinfo.h)
nil . nil) . (("system" stdlib.h)
nil . nil)) . (("tanf" math.h)
(("tan" math.h)
nil . nil) . (("tanh" math.h)
nil . nil))) . (("tcflow" unistd.h termios.h)
(("tanl" math.h)
(("tanhl" math.h)
nil . nil) . (("tcdrain" unistd.h termios.h)
nil . nil)) . (("tcgetattr" unistd.h termios.h)
(("tcflush" unistd.h termios.h)
nil . nil) . (("tcgetpgrp" unistd.h)
nil . nil)))) . (("tempnam" stdio.h)
(("tdelete" search.h)
(("tcsetattr" unistd.h termios.h)
(("tcsendbreak" unistd.h termios.h)
nil . nil) . (("tcsetpgrp" unistd.h)
nil . nil)) . (("tee" fcntl.h)
(("tdestroy" search.h)
nil . nil) . (("telldir" dirent.h)
nil . nil))) . (("tgammal" math.h)
(("tgamma" math.h)
(("tfind" search.h)
nil . nil) . (("tgammaf" math.h)
nil . nil)) . (("thrd_create" threads.h)
(("thrd_busy" threads.h)
nil . nil) . nil))))) . (("tmpnam" stdio.h)
(("timer_create" time.h signal.h)
(("thrd_t" threads.h)
(("thrd_exit" threads.h)
(("thrd_equal" threads.h)
(("thrd_detach" threads.h)
nil . nil) . (("thrd_error" threads.h)
nil . nil)) . (("thrd_start_t" threads.h)
(("thrd_nomem" threads.h)
nil . nil) . (("thrd_success" threads.h)
nil . nil))) . (("time" time.h)
(("thrd_yield" threads.h)
(("thrd_timeout" threads.h)
nil . nil) . (("thread_local" threads.h)
nil . nil)) . (("timegm" time.h)
(("time_t" time.h)
nil . nil) . (("timelocal" time.h)
nil . nil)))) . (("timerfd_create" sys/timerfd.h)
(("timer_settime" time.h)
(("timer_getoverrun" time.h)
(("timer_delete" time.h)
nil . nil) . (("timer_gettime" time.h)
nil . nil)) . (("timerclear" sys/time.h)
(("timeradd" sys/time.h)
nil . nil) . (("timercmp" sys/time.h)
nil . nil))) . (("timersub" sys/time.h)
(("timerfd_settime" sys/timerfd.h)
(("timerfd_gettime" sys/timerfd.h)
nil . nil) . (("timerisset" sys/time.h)
nil . nil)) . (("tmpfile" stdio.h)
(("times" sys/times.h)
nil . nil) . nil)))) . (("tss_get" threads.h)
(("truncate" unistd.h sys/types.h)
(("towctrans" wctype.h)
(("tolower" ctype.h)
(("toascii" ctype.h)
nil . nil) . (("toupper" ctype.h)
nil . nil)) . (("towupper" wctype.h)
(("towlower" wctype.h)
nil . nil) . (("trunc" math.h)
nil . nil))) . (("tss_create" threads.h)
(("truncl" math.h)
(("truncf" math.h)
nil . nil) . (("tsearch" search.h)
nil . nil)) . (("tss_dtor_t" threads.h)
(("tss_delete" threads.h)
nil . nil) . nil))) . (("uint32_t" stdint.h)
(("ttyslot" stdlib.h unistd.h)
(("ttyname" unistd.h)
(("tss_t" threads.h)
nil . nil) . (("ttyname_r" unistd.h)
nil . nil)) . (("ualarm" unistd.h)
(("twalk" search.h)
nil . nil) . (("uint16_t" stdint.h)
nil . nil))) . (("uint_fast32_t" stdint.h)
(("uint8_t" stdint.h)
(("uint64_t" stdint.h)
nil . nil) . (("uint_fast16_t" stdint.h)
nil . nil)) . (("uint_fast8_t" stdint.h)
(("uint_fast64_t" stdint.h)
nil . nil) . nil)))))) . (("wcpncpy" wchar.h)
(("vdprintf" stdio.h)
(("unsetenv" stdlib.h)
(("umount" sys/mount.h)
(("uintmax_t" stdint.h)
(("uint_least64_t" stdint.h)
(("uint_least32_t" stdint.h)
nil . nil) . (("uint_least8_t" stdint.h)
nil . nil)) . (("ulimit" ulimit.h)
(("uintptr_t" stdint.h)
nil . nil) . (("umask" sys/stat.h sys/types.h)
nil . nil))) . (("ungetwc" wchar.h)
(("uname" sys/utsname.h)
(("umount2" sys/mount.h)
nil . nil) . (("ungetc" stdio.h)
nil . nil)) . (("unlinkat" fcntl.h)
(("unlink" unistd.h)
nil . nil) . (("unlockpt" stdlib.h)
nil . nil)))) . (("utimes" sys/types.h sys/time.h utime.h)
(("usleep" unistd.h)
(("updwtmp" utmp.h)
(("unshare" sched.h)
nil . nil) . (("uselib" unistd.h)
nil . nil)) . (("utime" sys/types.h utime.h)
(("ustat" unistd.h sys/types.h ustat.h)
nil . nil) . (("utimensat" sys/stat.h)
nil . nil))) . (("va_start" stdarg.h)
(("va_copy" stdarg.h)
(("utmpname" utmp.h)
nil . nil) . (("va_end" stdarg.h)
nil . nil)) . (("vasprintf" stdio.h)
(("valloc" stdlib.h malloc.h)
nil . nil) . nil)))) . (("vswprintf" wchar.h)
(("vm86" sys/vm86.h)
(("vfprintf" stdio.h)
(("verrx" err.h stdarg.h)
(("verr" err.h stdarg.h)
nil . nil) . (("versionsort" dirent.h)
nil . nil)) . (("vfwprintf" wchar.h)
(("vfscanf" stdio.h)
nil . nil) . (("vfwscanf" wchar.h)
nil . nil))) . (("vscanf" stdio.h)
(("vmsplice" fcntl.h sys/uio.h)
(("vm86old" sys/vm86.h)
nil . nil) . (("vprintf" stdio.h)
nil . nil)) . (("vsprintf" stdio.h)
(("vsnprintf" stdio.h)
nil . nil) . (("vsscanf" stdio.h)
nil . nil)))) . (("wait3" sys/wait.h sys/resource.h sys/types.h sys/time.h)
(("vwarnx" err.h stdarg.h)
(("vsyslog" syslog.h stdarg.h)
(("vswscanf" wchar.h)
nil . nil) . (("vwarn" err.h stdarg.h)
nil . nil)) . (("vwscanf" wchar.h)
(("vwprintf" wchar.h)
nil . nil) . (("wait" sys/wait.h sys/types.h)
nil . nil))) . (("warn" err.h)
(("waitid" sys/wait.h sys/types.h)
(("wait4" sys/wait.h sys/resource.h sys/types.h sys/time.h)
nil . nil) . (("waitpid" sys/wait.h sys/types.h)
nil . nil)) . (("wcpcpy" wchar.h)
(("warnx" err.h)
nil . nil) . nil))))) . (("wcstoull" wchar.h)
(("wcsnrtombs" wchar.h)
(("wcscspn" wchar.h)
(("wcschr" wchar.h)
(("wcscasecmp" wchar.h)
(("wcrtomb" wchar.h)
nil . nil) . (("wcscat" wchar.h)
nil . nil)) . (("wcscoll" wchar.h)
(("wcscmp" wchar.h)
nil . nil) . (("wcscpy" wchar.h)
nil . nil))) . (("wcsncat" wchar.h)
(("wcslen" wchar.h)
(("wcsdup" wchar.h)
nil . nil) . (("wcsncasecmp" wchar.h)
nil . nil)) . (("wcsncpy" wchar.h)
(("wcsncmp" wchar.h)
nil . nil) . (("wcsnlen" wchar.h)
nil . nil)))) . (("wcstoimax" stddef.h inttypes.h)
(("wcsspn" wchar.h)
(("wcsrchr" wchar.h)
(("wcspbrk" wchar.h)
nil . nil) . (("wcsrtombs" wchar.h)
nil . nil)) . (("wcstod" wchar.h)
(("wcsstr" wchar.h)
nil . nil) . (("wcstof" wchar.h)
nil . nil))) . (("wcstoll" cwchar)
(("wcstol" cwchar)
(("wcstok" wchar.h)
nil . nil) . (("wcstold" wchar.h)
nil . nil)) . (("wcstoul" wchar.h)
(("wcstombs" stdlib.h)
nil . nil) . nil)))) . (("wordfree" wordexp.h)
(("wmemchr" wchar.h)
(("wctomb" stdlib.h)
(("wcswidth" wchar.h)
(("wcstoumax" stddef.h inttypes.h)
nil . nil) . (("wctob" wchar.h)
nil . nil)) . (("wctype" wctype.h)
(("wctrans" wctype.h)
nil . nil) . (("wcwidth" wchar.h)
nil . nil))) . (("wmempcpy" string.h wchar.h)
(("wmemcpy" wchar.h)
(("wmemcmp" wchar.h)
nil . nil) . (("wmemmove" wchar.h)
nil . nil)) . (("wordexp" wordexp.h)
(("wmemset" wchar.h)
nil . nil) . nil))) . (("y0l" math.h)
(("xdecrypt" rpc/des_crypt.h)
(("write" unistd.h)
(("wprintf" wchar.h)
nil . nil) . (("writev" sys/uio.h)
nil . nil)) . (("y0" math.h)
(("xencrypt" rpc/des_crypt.h)
nil . nil) . (("y0f" math.h)
nil . nil))) . (("yn" math.h)
(("y1f" math.h)
(("y1" math.h)
nil . nil) . (("y1l" math.h)
nil . nil)) . (("ynl" math.h)
(("ynf" math.h)
nil . nil) . nil)))))))))))
